head	 1.3;
branch   ;
access   ;
symbols  ;
locks    ; strict;
comment  @# @;


1.3
date	 1996.12.13.16.55.53;  author JAEMZ;  state Exp;
branches ;
next	 1.2;

1.2
date	 1996.04.08.16.51.20;  author TOML;  state Exp;
branches ;
next	 1.1;

1.1
date	 1996.01.19.14.07.00;  author JAEMZ;  state Exp;
branches ;
next	 ;


desc
@Makefile for screen dumper
@


1.3
log
@Added bmpdump
@
text
@#
# $Source: x:/prj/tech/libsrc/dump/rcs/makefile $
# $Revision: 1.2 $
# $Author: TOML $
# $Date: 1996/04/08 16:51:20 $
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = dump

dump_OBJS = filefind gifdump pcxdump bmpdump

dump_HDRS = dump.h

%include $(MRC)\make.rc

@


1.2
log
@*** empty log message ***
@
text
@d2 4
a5 4
# $Source: x:/prj/tech/libsrc/dump/RCS/makefile $
# $Revision: 1.1 $
# $Author: JAEMZ $
# $Date: 1996/01/19 14:07:00 $
d18 1
a18 1
dump_OBJS = filefind gifdump pcxdump
@


1.1
log
@Initial revision
@
text
@d2 4
a5 4
# $Source: t:/prj/tech/libsrc/gifd/rcs/makefile $
# $Revision: 2.1 $
# $Author: ept $
# $Date: 1995/10/02 20:01:22 $
@
