head	 1.2;
branch   ;
access   ;
symbols  ;
locks    ; strict;
comment  @# @;


1.2
date	 1996.05.03.15.10.21;  author TOML;  state Exp;
branches ;
next	 1.1;

1.1
date	 1996.05.01.17.00.11;  author TOML;  state Exp;
branches ;
next	 ;


desc
@@


1.2
log
@*** empty log message ***
@
text
@#
# $Source: x:/prj/tech/libsrc/templgen/rcs/makefile $
# $Revision: 1.1 $
# $Author: TOML $
# $Date: 1996/05/01 17:00:11 $
#
# Makefile for templgen library
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = templgen

templgen_OBJS = templ1

templgen_HDRS =

%include $(MRC)\make.rc
@


1.1
log
@Initial revision
@
text
@d2 4
a5 4
# $Source: $
# $Revision:  $
# $Author:  $
# $Date: $
d20 1
a20 1
COMTOOLS_OBJS = templ1
d22 1
a22 1
COMTOOLS_HDRS =
@
