// Debug header file x:\prj\tech\h/_2d.__h made from libdbg.dbg by DBGMAKEH

#ifndef ___2D_H
#define ___2D_H

#define DB_2D 1
#define DS_2D_Init 0x1
#define DSRC_2D_Init 0x8000001
#define DS_2D_Memory 0x2
#define DSRC_2D_Memory 0x8000002
#define DS_2D_Screen 0x4
#define DSRC_2D_Screen 0x8000004
#define DS_2D_Canvas 0x8
#define DSRC_2D_Canvas 0x8000008
#define DS_2D_Line 0x10
#define DSRC_2D_Line 0x8000010
#define DS_2D_Polygon 0x20
#define DSRC_2D_Polygon 0x8000020
#define DS_2D_SPolygon 0x40
#define DSRC_2D_SPolygon 0x8000040
#define DS_2D_CPolygon 0x80
#define DSRC_2D_CPolygon 0x8000080
#define DS_2D_Bitmap 0x100
#define DSRC_2D_Bitmap 0x8000100
#define DS_2D_ScaleBM 0x200
#define DSRC_2D_ScaleBM 0x8000200
#define DS_2D_Tmap 0x400
#define DSRC_2D_Tmap 0x8000400
#define DS_2D_Afile 0x100000
#define DSRC_2D_Afile 0x8100000
#define DS_2D_Movie 0x800000
#define DSRC_2D_Movie 0x8800000
#define DS_2D_MovDetl 0x1000000
#define DSRC_2D_MovDetl 0x9000000
#define DS_2D_Anim 0x2000000
#define DSRC_2D_Anim 0xa000000
#define DS_2D_AnimDetl 0x4000000
#define DSRC_2D_AnimDetl 0xc000000

#endif
