// Debug header file x:\prj\tech\h/_3d.__h made from libdbg.dbg by DBGMAKEH

#ifndef ___3D_H
#define ___3D_H

#define DB_3D 2
#define DS_3D_Project 0x1
#define DSRC_3D_Project 0x10000001
#define DS_3D_Clipping 0x2
#define DSRC_3D_Clipping 0x10000002
#define DS_3D_Lines 0x4
#define DSRC_3D_Lines 0x10000004
#define DS_3D_Polygons 0x8
#define DSRC_3D_Polygons 0x10000008
#define DS_3D_Horizon 0x10
#define DSRC_3D_Horizon 0x10000010
#define DS_3D_SHorizon 0x20
#define DSRC_3D_SHorizon 0x10000020
#define DS_3D_Setup 0x40
#define DSRC_3D_Setup 0x10000040
#define DS_3D_Xforms 0x80
#define DSRC_3D_Xforms 0x10000080
#define DS_3D_Pnt_Alloc 0x100
#define DSRC_3D_Pnt_Alloc 0x10000100
#define DS_3D_Matrix 0x200
#define DSRC_3D_Matrix 0x10000200
#define DS_3D_TextureMaps 0x400
#define DSRC_3D_TextureMaps 0x10000400
#define DS_3D_Statistics 0x800
#define DSRC_3D_Statistics 0x10000800

#endif
