; Debug header file x:\prj\tech\h/_babl2.__i made from libdbg.dbg by DBGMAKEH

DB_BABL2 equ 9
DS_BABL2_Tasks equ 01h
DSRC_BABL2_Tasks equ 048000001h
DS_BABL2_Source equ 02h
DSRC_BABL2_Source equ 048000002h
DS_BABL2_DebugVal equ 04h
DSRC_BABL2_DebugVal equ 048000004h
DS_BABL2_Interp equ 08h
DSRC_BABL2_Interp equ 048000008h
DS_BABL2_AppOps equ 010h
DSRC_BABL2_AppOps equ 048000010h
DS_BABL2_Compiler equ 020h
DSRC_BABL2_Compiler equ 048000020h
DS_BABL2_Linker equ 040h
DSRC_BABL2_Linker equ 048000040h
