// Debug header file x:\prj\tech\h/_network.__h made from libdbg.dbg by DBGMAKEH

#ifndef ___NETWORK_H
#define ___NETWORK_H

#define DB_NETWORK 4
#define DS_NETWORK_Check 0x1
#define DSRC_NETWORK_Check 0x20000001
#define DS_NETWORK_InitShut 0x2
#define DSRC_NETWORK_InitShut 0x20000002
#define DS_NETWORK_PackDump 0x4
#define DSRC_NETWORK_PackDump 0x20000004
#define DS_NETWORK_Update 0x8
#define DSRC_NETWORK_Update 0x20000008
#define DS_NETWORK_Admin 0x10
#define DSRC_NETWORK_Admin 0x20000010
#define DS_NETWORK_Game 0x20
#define DSRC_NETWORK_Game 0x20000020
#define DS_NETWORK_Node 0x40
#define DSRC_NETWORK_Node 0x20000040
#define DS_NETWORK_Watchdog 0x80
#define DSRC_NETWORK_Watchdog 0x20000080
#define DS_NETWORK_Time 0x100
#define DSRC_NETWORK_Time 0x20000100
#define DS_NETWORK_Object 0x400
#define DSRC_NETWORK_Object 0x20000400
#define DS_NETWORK_ObjAdmin 0x800
#define DSRC_NETWORK_ObjAdmin 0x20000800
#define DS_NETWORK_IPX 0x10000
#define DSRC_NETWORK_IPX 0x20010000
#define DS_NETWORK_TECB 0x20000
#define DSRC_NETWORK_TECB 0x20020000
#define DS_NETWORK_RMIH 0x2000000
#define DSRC_NETWORK_RMIH 0x22000000

#endif
