// Debug header file x:\prj\tech\h/_parse.__h made from libdbg.dbg by DBGMAKEH

#ifndef ___PARSE_H
#define ___PARSE_H

#define DB_PARSE 10
#define DS_PARSE_ParseGenl 0x1
#define DSRC_PARSE_ParseGenl 0x50000001
#define DS_PARSE_ParseDetl 0x2
#define DSRC_PARSE_ParseDetl 0x50000002
#define DS_PARSE_ParseExpr 0x4
#define DSRC_PARSE_ParseExpr 0x50000004
#define DS_PARSE_ParseComp 0x8
#define DSRC_PARSE_ParseComp 0x50000008
#define DS_PARSE_ParseCach 0x10
#define DSRC_PARSE_ParseCach 0x50000010
#define DS_PARSE_ScanGenl 0x20
#define DSRC_PARSE_ScanGenl 0x50000020
#define DS_PARSE_ScanDetl 0x40
#define DSRC_PARSE_ScanDetl 0x50000040
#define DS_PARSE_Cstreams 0x80
#define DSRC_PARSE_Cstreams 0x50000080

#endif
