; Debug header file x:\prj\tech\h/_parse.__i made from libdbg.dbg by DBGMAKEH

DB_PARSE equ 10
DS_PARSE_ParseGenl equ 01h
DSRC_PARSE_ParseGenl equ 050000001h
DS_PARSE_ParseDetl equ 02h
DSRC_PARSE_ParseDetl equ 050000002h
DS_PARSE_ParseExpr equ 04h
DSRC_PARSE_ParseExpr equ 050000004h
DS_PARSE_ParseComp equ 08h
DSRC_PARSE_ParseComp equ 050000008h
DS_PARSE_ParseCach equ 010h
DSRC_PARSE_ParseCach equ 050000010h
DS_PARSE_ScanGenl equ 020h
DSRC_PARSE_ScanGenl equ 050000020h
DS_PARSE_ScanDetl equ 040h
DSRC_PARSE_ScanDetl equ 050000040h
DS_PARSE_Cstreams equ 080h
DSRC_PARSE_Cstreams equ 050000080h
