// Debug header file x:\prj\tech\h/_sound.__h made from libdbg.dbg by DBGMAKEH

#ifndef ___SOUND_H
#define ___SOUND_H

#define DB_SOUND 7
#define DS_SOUND_Closures 0x1
#define DSRC_SOUND_Closures 0x38000001
#define DS_SOUND_Xsequences 0x2
#define DSRC_SOUND_Xsequences 0x38000002
#define DS_SOUND_samples 0x4
#define DSRC_SOUND_samples 0x38000004
#define DS_SOUND_tables 0x8
#define DSRC_SOUND_tables 0x38000008
#define DS_SOUND_SndSoundSources 0x10
#define DSRC_SOUND_SndSoundSources 0x38000010
#define DS_SOUND_MIDI 0x20
#define DSRC_SOUND_MIDI 0x38000020
#define DS_SOUND_SndMIDIDevices 0x40
#define DSRC_SOUND_SndMIDIDevices 0x38000040
#define DS_SOUND_SndMIDIChannels 0x80
#define DSRC_SOUND_SndMIDIChannels 0x38000080
#define DS_SOUND_SndSpeechChannels 0x100
#define DSRC_SOUND_SndSpeechChannels 0x38000100
#define DS_SOUND_asynch_updates 0x200
#define DSRC_SOUND_asynch_updates 0x38000200
#define DS_SOUND_synch_updates 0x400
#define DSRC_SOUND_synch_updates 0x38000400
#define DS_SOUND_SoundInit 0x800
#define DSRC_SOUND_SoundInit 0x38000800
#define DS_SOUND_SndDigi 0x1000
#define DSRC_SOUND_SndDigi 0x38001000
#define DS_SOUND_QSound 0x2000
#define DSRC_SOUND_QSound 0x38002000

#endif
