// Debug header file x:\prj\tech\h/_testlib.__h made from libdbg.dbg by DBGMAKEH

#ifndef ___TESTLIB_H
#define ___TESTLIB_H

#define DB_TESTLIB 15
#define DS_TESTLIB_Test0 0x1
#define DSRC_TESTLIB_Test0 0x78000001
#define DS_TESTLIB_Test1 0x2
#define DSRC_TESTLIB_Test1 0x78000002
#define DS_TESTLIB_Test2 0x4
#define DSRC_TESTLIB_Test2 0x78000004
#define DS_TESTLIB_Test3 0x8
#define DSRC_TESTLIB_Test3 0x78000008
#define DS_TESTLIB_Test4 0x10
#define DSRC_TESTLIB_Test4 0x78000010
#define DS_TESTLIB_Test5 0x20
#define DSRC_TESTLIB_Test5 0x78000020
#define DS_TESTLIB_Test6 0x40
#define DSRC_TESTLIB_Test6 0x78000040
#define DS_TESTLIB_Test7 0x80
#define DSRC_TESTLIB_Test7 0x78000080
#define DS_TESTLIB_Test8 0x100
#define DSRC_TESTLIB_Test8 0x78000100
#define DS_TESTLIB_Test9 0x200
#define DSRC_TESTLIB_Test9 0x78000200

#endif
