/*
 * BASETYPE: Header to define the basic types that shall be used by all
 *           of the files needed by the JPEG modules.
 */

typedef unsigned char  uInt8;

typedef   signed char  sInt8;

typedef unsigned char  uByte;

typedef   signed char  sByte;
  
typedef unsigned short uInt16;

typedef   signed short sInt16;

typedef unsigned short uWord;

typedef   signed short sWord;

typedef unsigned int   uInt32;

typedef   signed int   sInt32;

typedef unsigned int   uDWord;

typedef   signed int   sDWord;

