/*
 * $Source: r:/prj/lib/src/det/RCS/detect.h $
 * $Revision: 1.1 $
 * $Author: jaemz $
 * $Date: 1994/10/25 02:12:22 $
 *
 * $Log: detect.h $
 * Revision 1.1  1994/10/25  02:12:22  jaemz
 * Initial revision
 * 
 * Revision 1.1  1994/10/25  02:10:34  jaemz
 * Initial revision
 * 
*/

#ifndef __DETECT_H
#define __DETECT_H

int dt_language();
int dt_keyboard();
int dt_country();
                  
#endif /* __DETECT_H */
