
# $Source: x:/prj/tech/libsrc/dstruct/RCS/makefile $
# $Revision: 2.2 $
# $Author: TOML $
# $Date: 1996/04/08 16:51:13 $

MAKETOP = $(CWD)

PROJECT = tech 

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = dstruct

DSTRUCT_OBJS = array fname hash hheap huffde huffen llist lllist \
	message pqueue rect strall  symdump symtab 

DSTRUCT_HDRS = array.h fname.h hash.h hheap.h huff.h huffde.h llist.h \
	message.h pqueue.h rect.h slist.h strall.h symtab.h

%include $(MRC)\make.rc

