#
# $Source: x:/prj/tech/libsrc/entrywin/RCS/makefile $
# $Revision: 1.2 $
# $Author: TOML $
# $Date: 1996/06/11 13:49:13 $
#
# Makefile for entrywin library
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = entrywin

ENTRYWIN_OBJS = entrywin

ENTRYWIN_HDRS =

%include $(MRC)\make.rc
