#
# $Source: x:/prj/tech/libsrc/actmovie/RCS/makefile $
# $Revision: 1.9 $
# $Author: TOML $
# $Date: 1996/10/22 13:15:35 $
#
# Makefile for actmovie library
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = actmovie

actmovie_DEFINES =

actmovie_OBJS = actmovie

actmovie_win32_OBJS = amguids amalloc imutil mtype getlgvid

actmovie_opt_objs = imutil

actmovie_HDRS =

%include $(MRC)\make.rc

