#
# $Source: x:/prj/tech/libsrc/gameshel/RCS/makefile $
# $Revision: 1.9 $
# $Author: TOML $
# $Date: 1996/10/21 17:10:41 $
#
# Makefile for winshell library
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = gameshel

gameshel_win32_OBJS = wgshell wgshelmt winput wgscreat
gameshel_dos4g_OBJS = dgshell

gameshel_HDRS = wnshguid.h winshapi.h

%include $(MRC)\make.rc

