; Debug header file x:\prj\tech\inc/_3d.__i made from libdbg.dbg by DBGMAKEH

DB_3D equ 2
DS_3D_Project equ 01h
DSRC_3D_Project equ 010000001h
DS_3D_Clipping equ 02h
DSRC_3D_Clipping equ 010000002h
DS_3D_Lines equ 04h
DSRC_3D_Lines equ 010000004h
DS_3D_Polygons equ 08h
DSRC_3D_Polygons equ 010000008h
DS_3D_Horizon equ 010h
DSRC_3D_Horizon equ 010000010h
DS_3D_SHorizon equ 020h
DSRC_3D_SHorizon equ 010000020h
DS_3D_Setup equ 040h
DSRC_3D_Setup equ 010000040h
DS_3D_Xforms equ 080h
DSRC_3D_Xforms equ 010000080h
DS_3D_Pnt_Alloc equ 0100h
DSRC_3D_Pnt_Alloc equ 010000100h
DS_3D_Matrix equ 0200h
DSRC_3D_Matrix equ 010000200h
DS_3D_TextureMaps equ 0400h
DSRC_3D_TextureMaps equ 010000400h
DS_3D_Statistics equ 0800h
DSRC_3D_Statistics equ 010000800h
