head	 1.13;
branch   ;
access   ;
symbols  ;
locks    TOML:1.13; strict;
comment  @# @;


1.13
date	 1997.02.24.23.47.54;  author TOML;  state Exp;
branches ;
next	 1.12;

1.12
date	 1996.11.05.09.08.59;  author TOML;  state Exp;
branches ;
next	 1.11;

1.11
date	 1996.09.19.18.43.26;  author JON;  state Exp;
branches ;
next	 1.10;

1.10
date	 1996.08.13.14.25.46;  author TOML;  state Exp;
branches ;
next	 1.9;

1.9
date	 1996.08.12.15.44.10;  author TOML;  state Exp;
branches ;
next	 1.8;

1.8
date	 1996.08.06.16.03.10;  author TOML;  state Exp;
branches ;
next	 1.7;

1.7
date	 1996.07.17.11.35.01;  author TOML;  state Exp;
branches ;
next	 1.6;

1.6
date	 1996.07.01.16.03.26;  author TOML;  state Exp;
branches ;
next	 1.5;

1.5
date	 1996.06.20.17.13.16;  author TOML;  state Exp;
branches ;
next	 1.4;

1.4
date	 1996.05.07.08.50.31;  author TOML;  state Exp;
branches ;
next	 1.3;

1.3
date	 1996.05.06.16.03.00;  author TOML;  state Exp;
branches ;
next	 1.2;

1.2
date	 1996.05.02.12.30.22;  author TOML;  state Exp;
branches ;
next	 1.1;

1.1
date	 1996.04.23.09.38.20;  author TOML;  state Exp;
branches ;
next	 ;


desc
@@


1.13
log
@Initial cache API
@
text
@#
# $Source: x:/prj/tech/libsrc/compapis/rcs/makefile $
# $Revision: 1.12 $
# $Author: TOML $
# $Date: 1996/11/05 09:08:59 $
#
# Makefile for compapis ibrary
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = compapis

compapis_OBJS = genguid1

compapis_HDRS = appagg.h appapi.h appguid.h dispapi.h dispguid.h gshelapi.h \
                gshlguid.h indevapi.h indvguid.h wappapi.h wappguid.h \
                pumpenum.h loopguid.h loopapi.h looptype.h movieapi.h \
                moviguid.h recapi.h recguid.h arqapi.h arqguid.h \
                movconst.h thrmnapi.h thrmguid.h cacheapi.h cachguid.h 

%include $(MRC)\make.rc


@


1.12
log
@*** empty log message ***
@
text
@d3 3
a5 3
# $Revision: 1.11 $
# $Author: JON $
# $Date: 1996/09/19 18:43:26 $
d26 1
a26 1
                movconst.h thrmnapi.h thrmguid.h
@


1.11
log
@Added movconst.h
@
text
@d3 3
a5 3
# $Revision: 1.10 $
# $Author: TOML $
# $Date: 1996/08/13 14:25:46 $
d26 1
a26 2
		movconst.h

@


1.10
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.9 $
d5 1
a5 1
# $Date: 1996/08/12 15:44:10 $
d25 2
a26 1
                moviguid.h recapi.h recguid.h arqapi.h arqguid.h
@


1.9
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.8 $
d5 1
a5 1
# $Date: 1996/08/06 16:03:10 $
d25 1
a25 1
                moviguid.h recapi.h recguid.h
@


1.8
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.7 $
d5 1
a5 1
# $Date: 1996/07/17 11:35:01 $
d25 1
a25 1
                moviguid.h
@


1.7
log
@API adjustment
@
text
@d3 1
a3 1
# $Revision: 1.6 $
d5 1
a5 1
# $Date: 1996/07/01 16:03:26 $
d24 2
a25 1
                pumpenum.h loopguid.h loopapi.h looptype.h
@


1.6
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.5 $
d5 1
a5 1
# $Date: 1996/06/20 17:13:16 $
d20 1
a20 1
compapis_OBJS = genguid1 lguuid
d23 1
a23 1
                gshlguid.h indevapi.h indvguid.h wappapi.h wappguid.h lguuid.h \
@


1.5
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.4 $
d5 1
a5 1
# $Date: 1996/05/07 08:50:31 $
d24 1
a24 1
                pumpenum.h loopguid.h loopapi.h looptype.h loopenum.h
@


1.4
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.3 $
d5 1
a5 1
# $Date: 1996/05/06 16:03:00 $
d24 1
a24 1
                pumpenum.h
@


1.3
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.2 $
d5 1
a5 1
# $Date: 1996/05/02 12:30:22 $
d23 1
a23 1
                gshlguid.h inmanapi.h inmnguid.h wappapi.h wappguid.h lguuid.h \
@


1.2
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.1 $
d5 1
a5 1
# $Date: 1996/04/23 09:38:20 $
d23 2
a24 1
                gshlguid.h inmanapi.h inmnguid.h wappapi.h wappguid.h lguuid.h
@


1.1
log
@Initial revision
@
text
@d2 4
a5 4
# $Source: $
# $Revision: $
# $Author: $
# $Date: $
d20 1
a20 1
compapis_OBJS = genguid1
d23 1
a23 1
                gshlguid.h inmanapi.h inmnguid.h wappapi.h wappguid.h
@
