# $Source: x:/prj/tech/libsrc/config/RCS/makefile $
# $Revision: 2.4 $
# $Author: TOML $
# $Date: 1996/04/08 16:50:29 $

MAKETOP = $(CWD)

PROJECT = tech 

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = config

config_OBJS = config cfg

config_HDRS = config.h cfgdbg.h cfg.h

%include $(MRC)\make.rc


