#
# $Source: x:/prj/tech/libsrc/star/RCS/makefile $
# $Revision: 2.4 $
# $Author: JAEMZ $
# $Date: 1997/08/12 22:34:58 $
#
# Makefile for Star library
#
# $Log: makefile $
# Revision 2.4  1997/08/12  22:34:58  JAEMZ
# Took out star3d.asm
# 
# Revision 2.3  1997/01/31  23:26:07  JAEMZ
# Ported star library to new libraries
# 
# Revision 2.2  1995/10/18  12:58:49  ept
# Typo fixed.
# 
# Revision 2.1  1995/10/18  12:57:56  ept
# This is the makefile for the new make system.
# 
# Revision 1.1.1.1  1995/03/20  16:14:41  jaemz
# New make system
# 
# Revision 1.1  1994/10/24  23:27:56  jaemz
# Initial revision
# 
#

MAKETOP = $(CWD)

PROJECT = tech 

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = star 

star_OBJS = star 
star_HDRS = star.h 

%include $(INIT)/make.rc

