#
# $Source: x:/prj/tech/libsrc/templgen/RCS/makefile $
# $Revision: 1.2 $
# $Author: TOML $
# $Date: 1996/05/03 15:10:21 $
#
# Makefile for templgen library
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = templgen

templgen_OBJS = templ1

templgen_HDRS =

%include $(MRC)\make.rc
