head	 1.3;
branch   ;
access   ;
symbols  ;
locks    ; strict;
comment  @# @;


1.3
date	 1996.11.21.13.11.59;  author kate;  state Exp;
branches ;
next	 1.2;

1.2
date	 1996.11.11.18.18.12;  author kate;  state Exp;
branches ;
next	 1.1;

1.1
date	 1996.10.30.11.32.51;  author kate;  state Exp;
branches ;
next	 ;


desc
@makefile for multiped library
@


1.3
log
@new mpvm module
@
text
@// $Header: x:/prj/tech/libsrc/mp/rcs/makefile 1.2 1996/11/11 18:18:12 kate Exp $

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = mp

mp_DEFINES =

mp_OBJS = qt mpinit mplist mpmot mpstack mpupdate mploco mpvm

mp_HDRS = mp.h multiped.h qt.h motion.h motstruc.h mputil.h mpstack.h mplist.h

%include $(MRC)\make.rc





@


1.2
log
@added loco
@
text
@d1 1
a1 1
// $Header: x:/prj/tech/libsrc/mp/rcs/makefile 1.1 1996/10/30 11:32:51 kate Exp $
d15 1
a15 1
mp_OBJS = qt mpinit mplist mpmot mpstack mpupdate mploco
@


1.1
log
@Initial revision
@
text
@d1 1
a1 1
// $Header: $
d15 1
a15 1
mp_OBJS = multiped qt mpinit mplist mpmot mpstack mpupdate 
@
