#
# $Source: x:/prj/tech/libsrc/dump/RCS/makefile $
# $Revision: 1.3 $
# $Author: JAEMZ $
# $Date: 1996/12/13 16:55:53 $
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = dump

dump_OBJS = filefind gifdump pcxdump bmpdump

dump_HDRS = dump.h

%include $(MRC)\make.rc

