#
# $Source: x:/prj/tech/libsrc/ui/RCS/makefile $
# $Revision: 2.2 $
# $Author: TOML $
# $Date: 1996/04/08 16:55:28 $

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = ui

irrupt_OBJS = curdrw

ui_OBJS = butarray curdrw cursors event gadgets hotkey menu plain \
	pushbutt qboxgadg region slab slider textgadg texttool tng \
	tngbarry tngfont tngmenu tngplain tngpushb tngqbox tngslidr tngtextg \
	uires vmouse

ui_HDRS = butarray.h curdat.h cursors.h curtyp.h event.h gadgets.h hotkey.h menu.h \
	plain.h pushbutt.h qboxgadg.h region.h slab.h slider.h textgadg.h texttool.h \
	tng.h tngapp.h tngbarry.h tngmenu.h tngplain.h tngpushb.h tngqbox.h tngslidr.h \
	tngtextg.h uires.h vmouse.h


%include $(MRC)\make.rc

