head	 1.1;
branch   ;
access   ;
symbols  ;
locks    ; strict;
comment  @# @;


1.1
date	 1997.08.22.19.39.12;  author kate;  state Exp;
branches ;
next	 ;


desc
@makefile
@



1.1
log
@Initial revision
@
text
@// $Header: $

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = mm

mm_OBJS = render sortpoly xformseg debug
#utils light

mm_HDRS= mms.h mm.h mmd.h

%include $(MRC)\make.rc


@
