head	 1.14;
branch   ;
access   ;
symbols  ;
locks    ; strict;
comment  @# @;


1.14
date	 1998.02.19.10.34.43;  author TOML;  state Exp;
branches ;
next	 1.13;

1.13
date	 1996.07.17.11.34.01;  author TOML;  state Exp;
branches ;
next	 1.12;

1.12
date	 1996.06.26.12.16.59;  author TOML;  state Exp;
branches ;
next	 1.11;

1.11
date	 1996.06.20.12.46.01;  author TOML;  state Exp;
branches ;
next	 1.10;

1.10
date	 1996.05.09.10.16.23;  author TOML;  state Exp;
branches ;
next	 1.9;

1.9
date	 1996.05.09.09.15.41;  author TOML;  state Exp;
branches ;
next	 1.8;

1.8
date	 1996.05.02.15.24.12;  author TOML;  state Exp;
branches ;
next	 1.7;

1.7
date	 1996.04.24.17.00.29;  author TOML;  state Exp;
branches ;
next	 1.6;

1.6
date	 1996.04.23.14.06.21;  author TOML;  state Exp;
branches ;
next	 1.5;

1.5
date	 1996.04.23.13.57.34;  author TOML;  state Exp;
branches ;
next	 1.4;

1.4
date	 1996.04.23.11.15.05;  author TOML;  state Exp;
branches ;
next	 1.3;

1.3
date	 1996.04.22.18.06.17;  author TOML;  state Exp;
branches ;
next	 1.2;

1.2
date	 1996.04.08.16.50.24;  author TOML;  state Exp;
branches ;
next	 1.1;

1.1
date	 1996.01.24.11.16.42;  author TOML;  state Exp;
branches ;
next	 ;


desc
@@


1.14
log
@quiet annoying weatcom warning
@
text
@#
# $Source: x:/prj/tech/libsrc/comtools/rcs/makefile $
# $Revision: 1.13 $
# $Author: TOML $
# $Date: 1996/07/17 11:34:01 $
#
# Makefile for comtools library
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = comtools

COMTOOLS_OBJS = comtools genagg geniset interset pintarr pguidset comconn

COMTOOLS_HDRS = comtools.h objcoll.h objcguid.h interset.h genagg.h \
                geniset.h pguidset.h pintarr.h constrid.h aggmemb.h \
                comconn.h

%include $(MRC)\make.rc
@


1.13
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.12 $
d5 1
a5 1
# $Date: 1996/06/26 12:16:59 $
d20 1
a20 1
COMTOOLS_OBJS = genagg geniset interset pintarr pguidset comconn
@


1.12
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.11 $
d5 1
a5 1
# $Date: 1996/06/20 12:46:01 $
d20 1
a20 1
COMTOOLS_OBJS = genagg geniset interset pintarr pguidset
d22 3
a24 1
COMTOOLS_HDRS = comtools.h objcoll.h objcguid.h interset.h genagg.h geniset.h pguidset.h pintarr.h constrid.h aggmemb.h
@


1.11
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.10 $
d5 1
a5 1
# $Date: 1996/05/09 10:16:23 $
d20 1
a20 1
COMTOOLS_OBJS = genagg geniset interset pintarr
d22 1
a22 1
COMTOOLS_HDRS = comtools.h objcoll.h objcguid.h interset.h genagg.h geniset.h pintarr.h prikind.h aggmemb.h
@


1.10
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.9 $
d5 1
a5 1
# $Date: 1996/05/09 09:15:41 $
d20 1
a20 1
COMTOOLS_OBJS = genagg geniset interset
d22 1
a22 1
COMTOOLS_HDRS = comtools.h objcoll.h objcguid.h interset.h genagg.h geniset.h
@


1.9
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.8 $
d5 1
a5 1
# $Date: 1996/05/02 15:24:12 $
d22 1
a22 2
COMTOOLS_HDRS = comtools.h objcoll.h objcguid.h interset.h genagg.h geniset.h \
                comntfy.h
@


1.8
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.7 $
d5 1
a5 1
# $Date: 1996/04/24 17:00:29 $
d22 2
a23 1
COMTOOLS_HDRS = comtools.h objcoll.h objcguid.h interset.h genagg.h geniset.h
@


1.7
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.6 $
d5 1
a5 1
# $Date: 1996/04/23 14:06:21 $
d20 1
a20 1
COMTOOLS_OBJS = genagg geniset
d22 1
a22 1
COMTOOLS_HDRS = comtools.h objcoll.h objcguid.h
@


1.6
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.5 $
d5 1
a5 1
# $Date: 1996/04/23 13:57:34 $
d22 1
a22 1
COMTOOLS_HDRS = comtools.h objcoll.h
@


1.5
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.4 $
d5 1
a5 1
# $Date: 1996/04/23 11:15:05 $
d22 1
a22 1
COMTOOLS_HDRS = comtools.h com.h
@


1.4
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.3 $
d5 1
a5 1
# $Date: 1996/04/22 18:06:17 $
d20 1
a20 1
COMTOOLS_OBJS = genagg ifaceset
d22 1
a22 1
COMTOOLS_HDRS = comtools.h genagg.h ifaceset.h
@


1.3
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.2 $
d5 1
a5 1
# $Date: 1996/04/08 16:50:24 $
d20 1
a20 1
COMTOOLS_OBJS = genagg
d22 1
a22 1
COMTOOLS_HDRS = comtools.h
@


1.2
log
@*** empty log message ***
@
text
@d2 2
a3 2
# $Source: x:/prj/tech/libsrc/comtools/RCS/makefile $
# $Revision: 1.1 $
d5 1
a5 1
# $Date: 1996/01/24 11:16:42 $
d19 2
@


1.1
log
@Initial revision
@
text
@d2 2
a3 2
# $Source: x:/prj/windex/libsrc/comtools/rcs/makefile $
# $Revision: 1.2 $
d5 1
a5 1
# $Date: 1996/01/22 15:08:09 $
d12 1
a12 1
PROJECT = windex
@
