# 
# $Source: x:/prj/tech/libsrc/rnd/RCS/makefile $
# $Revision: 2.2 $
# $Author: TOML $
# $Date: 1996/04/08 16:54:42 $
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = rnd

rnd_OBJS = rnd
rnd_HDRS = rnd.h

%include $(MRC)\make.rc


