call r:\prj\cam\reltools\init.bat

%_PRJPATH_%\bin\misstrip %_PRJPATH_%\levels\shipping\miss1.mis %_DAILYTHIEF_%\miss1.mis
%_PRJPATH_%\bin\misstrip %_PRJPATH_%\levels\shipping\miss2.mis %_DAILYTHIEF_%\miss2.mis
%_PRJPATH_%\bin\misstrip %_PRJPATH_%\levels\shipping\miss3.mis %_DAILYTHIEF_%\miss3.mis
%_PRJPATH_%\bin\misstrip %_PRJPATH_%\levels\shipping\miss4.mis %_DAILYTHIEF_%\miss4.mis
%_PRJPATH_%\bin\misstrip %_PRJPATH_%\levels\shipping\miss5.mis %_DAILYTHIEF_%\miss5.mis
%_PRJPATH_%\bin\misstrip %_PRJPATH_%\levels\shipping\miss6.mis %_DAILYTHIEF_%\miss6.mis
%_PRJPATH_%\bin\misstrip %_PRJPATH_%\levels\shipping\miss7.mis %_DAILYTHIEF_%\miss7.mis
%_PRJPATH_%\bin\misstrip %_PRJPATH_%\levels\shipping\miss9.mis %_DAILYTHIEF_%\miss9.mis
%_PRJPATH_%\bin\misstrip %_PRJPATH_%\levels\shipping\miss10.mis %_DAILYTHIEF_%\miss10.mis
%_PRJPATH_%\bin\misstrip %_PRJPATH_%\levels\shipping\miss11.mis %_DAILYTHIEF_%\miss11.mis
%_PRJPATH_%\bin\misstrip %_PRJPATH_%\levels\shipping\miss12.mis %_DAILYTHIEF_%\miss12.mis
%_PRJPATH_%\bin\misstrip %_PRJPATH_%\levels\shipping\miss13.mis %_DAILYTHIEF_%\miss13.mis
%_PRJPATH_%\bin\misstrip %_PRJPATH_%\levels\shipping\miss14.mis %_DAILYTHIEF_%\miss14.mis
