head	 1.1;
branch   ;
access   ;
symbols  ;
locks    ; strict;
comment  @REM @;


1.1
date	 1999.10.05.18.29.38;  author adurant;  state Exp;
branches ;
next	 ;


desc
@@



1.1
log
@Initial revision
@
text
@set _orig_=%1


copy r:\prj\cam\%_orig_%\cd\thief\*.bnd
copy r:\prj\cam\%_orig_%\cd\thief\*.cfg
copy r:\prj\cam\%_orig_%\cd\thief\*.osm
copy r:\prj\cam\%_orig_%\cd\thief\*.res
copy r:\prj\cam\%_orig_%\cd\thief\*.dll
copy r:\prj\cam\%_orig_%\cd\thief\*.exe


@
