head	 1.2;
branch   ;
access   ;
symbols  ;
locks    ; strict;
comment  @@;


1.2
date	 2000.02.24.20.05.30;  author adurant;  state Exp;
branches ;
next	 1.1;

1.1
date	 1999.10.05.18.30.14;  author adurant;  state Exp;
branches ;
next	 ;


desc
@exclude
@


1.2
log
@min on cd2
@
text
@.\movies\
fam.crf
miss1.mis
miss2.mis
miss4.mis
miss5.mis
miss6.mis
miss7.mis
miss8.mis
miss9.mis
miss10.mis
miss11.mis
miss12.mis
miss13.mis
miss14.mis
miss15.mis
miss16.mis
miss1.osm
miss2.osm
miss4.osm
miss5.osm
miss6.osm
miss7.osm
miss8.osm
miss9.osm
miss10.osm
miss11.osm
miss12.osm
miss13.osm
miss14.osm
miss15.osm
miss16.osm

@


1.1
log
@Initial revision
@
text
@d1 32
a32 1

@
