head	 1.1;
branch   ;
access   ;
symbols  ;
locks    ; strict;
comment  @REM @;


1.1
date	 1999.10.05.18.29.39;  author adurant;  state Exp;
branches ;
next	 ;


desc
@@



1.1
log
@Initial revision
@
text
@@@rem $Header: r:/prj/cam/reltools/RCS/mkcd1.bat 1.15 1998/10/03 00:27:33 DAVET Exp $



call r:\prj\cam\reltools\init.bat
call r:\prj\cam\reltools\src.bat
call r:\prj\cam\reltools\content.bat@
