head	 1.5;
branch   ;
access   ;
symbols  ;
locks    ; strict;
comment  @# @;


1.5
date	 1997.02.15.17.44.43;  author TOML;  state Exp;
branches ;
next	 1.4;

1.4
date	 1996.10.22.13.16.28;  author TOML;  state Exp;
branches ;
next	 1.3;

1.3
date	 1996.06.11.14.32.58;  author TOML;  state Exp;
branches ;
next	 1.2;

1.2
date	 1996.04.25.10.01.53;  author TOML;  state Exp;
branches ;
next	 1.1;

1.1
date	 1996.04.22.11.33.07;  author TOML;  state Exp;
branches ;
next	 ;


desc
@@


1.5
log
@*** empty log message ***
@
text
@#
# $Source: x:/prj/tech/libsrc/appcore/rcs/makefile $
# $Revision: 1.4 $
# $Author: TOML $
# $Date: 1996/10/22 13:16:28 $
#
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = appcore

EXETARGS =

appcore_OBJS = appcore dappcore wappcore defcreat definit defexit appflags

appcore_HDRS =

%include $(MRC)\make.rc
@


1.4
log
@Backport to DOS
@
text
@d3 1
a3 1
# $Revision: 1.3 $
d5 1
a5 1
# $Date: 1996/06/11 14:32:58 $
d21 1
a21 1
appcore_OBJS = appcore dappcore wappcore defcreat definit defexit
@


1.3
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.2 $
d5 1
a5 1
# $Date: 1996/04/25 10:01:53 $
d21 1
a21 1
appcore_OBJS = appcore wappcore defcreat definit defexit
@


1.2
log
@*** empty log message ***
@
text
@d2 2
a3 2
# $Source: x:/prj/tech/libsrc/appcore/RCS/makefile $
# $Revision: 1.1 $
d5 1
a5 1
# $Date: 1996/04/22 11:33:07 $
d21 1
a21 1
appcore_OBJS = appcore wappcore
@


1.1
log
@Initial revision
@
text
@d2 4
a5 4
# $Source: $
# $Revision: $
# $Author: $
# $Date: $
d21 1
a21 1
appcore_OBJS = appcore
@
