head	 1.9;
branch   ;
access   ;
symbols  ;
locks    ; strict;
comment  @# @;


1.9
date	 1996.10.21.17.10.41;  author TOML;  state Exp;
branches ;
next	 1.8;

1.8
date	 1996.10.21.15.08.57;  author TOML;  state Exp;
branches ;
next	 1.7;

1.7
date	 1996.10.21.15.00.51;  author TOML;  state Exp;
branches ;
next	 1.6;

1.6
date	 1996.09.18.16.45.09;  author TOML;  state Exp;
branches ;
next	 1.5;

1.5
date	 1996.05.08.17.40.49;  author TOML;  state Exp;
branches ;
next	 1.4;

1.4
date	 1996.05.08.15.19.34;  author TOML;  state Exp;
branches ;
next	 1.3;

1.3
date	 1996.05.08.10.13.07;  author TOML;  state Exp;
branches ;
next	 1.2;

1.2
date	 1996.05.06.16.02.01;  author TOML;  state Exp;
branches ;
next	 1.1;

1.1
date	 1996.05.04.17.53.32;  author TOML;  state Exp;
branches ;
next	 ;


desc
@@


1.9
log
@*** empty log message ***
@
text
@#
# $Source: x:/prj/tech/libsrc/gameshel/rcs/makefile $
# $Revision: 1.8 $
# $Author: TOML $
# $Date: 1996/10/21 15:08:57 $
#
# Makefile for winshell library
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = gameshel

gameshel_win32_OBJS = wgshell wgshelmt winput wgscreat
gameshel_dos4g_OBJS = dgshell

gameshel_HDRS = wnshguid.h winshapi.h

%include $(MRC)\make.rc

@


1.8
log
@*** empty log message ***
@
text
@d2 2
a3 2
# $Source: x:/prj/tech/libsrc/gameshel/win/rcs/makefile $
# $Revision: 1.7 $
d5 1
a5 1
# $Date: 1996/10/21 15:00:51 $
d20 2
a21 1
gameshel_OBJS = wgshell wgshelmt winput wgscreat
@


1.7
log
@*** empty log message ***
@
text
@d2 2
a3 2
# $Source: x:/prj/tech/libsrc/gameshel/win/RCS/makefile $
# $Revision: 1.6 $
d5 1
a5 1
# $Date: 1996/09/18 16:45:09 $
d20 1
a20 1
winshell_OBJS = wgshell wgshelmt winput wgscreat
d22 1
a22 1
winshell_HDRS = wnshguid.h winshapi.h
@


1.6
log
@*** empty log message ***
@
text
@d2 2
a3 2
# $Source: x:/prj/tech/libsrc/winshell/rcs/makefile $
# $Revision: 1.5 $
d5 1
a5 1
# $Date: 1996/05/08 17:40:49 $
d18 1
a18 1
LIBTARGS = winshell
@


1.5
log
@*** empty log message ***
@
text
@d2 2
a3 2
# $Source: x:/prj/tech/libsrc/winshell/RCS/makefile $
# $Revision: 1.4 $
d5 1
a5 1
# $Date: 1996/05/08 15:19:34 $
d20 1
a20 1
winshell_OBJS = wgshell winput
@


1.4
log
@*** empty log message ***
@
text
@d2 2
a3 2
# $Source: x:/prj/tech/libsrc/winshell/rcs/makefile $
# $Revision: 1.3 $
d5 1
a5 1
# $Date: 1996/05/08 10:13:07 $
d20 1
a20 1
winshell_OBJS = WDISP wdispdd wdispgdi WGSHELL WINPUT
@


1.3
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.2 $
d5 1
a5 1
# $Date: 1996/05/06 16:02:01 $
d22 1
a22 1
winshell_HDRS = wnshguid.h
@


1.2
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.1 $
d5 1
a5 1
# $Date: 1996/05/04 17:53:32 $
d22 1
a22 1
winshell_HDRS =
@


1.1
log
@Initial revision
@
text
@d2 4
a5 4
# $Source: $
# $Revision: $
# $Author: $
# $Date:$
d20 1
a20 1
winshell_OBJS =
d25 1
@
