#	----------------------------------
#	Makefile for GFILE library
#	----------------------------------
#
# $Header: x:/prj/tech/libsrc/gfile/RCS/makefile 2.1 1995/10/02 20:00:08 ept Exp $

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = gfile 

gfile_OBJS = gfile pcx gif cel bmp

gfile_HDRS = gfile.h

%include $(MRC)\make.rc