#
# $Source: x:/prj/tech/libsrc/appcore/RCS/makefile $
# $Revision: 1.5 $
# $Author: TOML $
# $Date: 1997/02/15 17:44:43 $
#
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = appcore

EXETARGS =

appcore_OBJS = appcore dappcore wappcore defcreat definit defexit appflags

appcore_HDRS =

%include $(MRC)\make.rc
