head	 1.2;
branch   ;
access   ;
symbols  ;
locks    ; strict;
comment  @# @;


1.2
date	 1996.06.11.13.49.13;  author TOML;  state Exp;
branches ;
next	 1.1;

1.1
date	 1996.06.11.13.48.09;  author TOML;  state Exp;
branches ;
next	 ;


desc
@@


1.2
log
@*** empty log message ***
@
text
@#
# $Source: x:/prj/tech/libsrc/entrywin/rcs/makefile $
# $Revision: 1.1 $
# $Author: TOML $
# $Date: 1996/06/11 13:48:09 $
#
# Makefile for entrywin library
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = entrywin

ENTRYWIN_OBJS = entrywin

ENTRYWIN_HDRS =

%include $(MRC)\make.rc
@


1.1
log
@Initial revision
@
text
@d2 2
a3 2
# $Source: x:/prj/tech/libsrc/comtools/rcs/makefile $
# $Revision: 1.10 $
d5 1
a5 1
# $Date: 1996/05/09 10:16:23 $
d20 1
a20 1
COMTOOLS_OBJS = entrywin
d22 1
a22 1
COMTOOLS_HDRS =
@
