head	 1.2;
branch   ;
access   ;
symbols  ;
locks    ; strict;
comment  @# @;


1.2
date	 1996.10.10.17.48.36;  author JON;  state Exp;
branches ;
next	 1.1;

1.1
date	 1996.10.10.17.38.47;  author JON;  state Exp;
branches ;
next	 ;


desc
@@


1.2
log
@Fix header entry.
@
text
@# $Source: x:/prj/tech/libsrc/vec2/rcs/makefile $
# $Revision: 1.1 $
# $Author: JON $
# $Date: 1996/10/10 17:38:47 $

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = vec2

vec2_OBJS = vec2

vec2_HDRS = vec2.h

%include $(MRC)\make.rc
@


1.1
log
@Initial revision
@
text
@d1 1
a1 1
# $Source: o:/prj/tech/libsrc/vec2/RCS/makefile $
d4 1
a4 1
# $Date: 1996/10/10 17:32:10 $
d18 1
a18 1
vec2_HDRS = vec2
@
