# $Header: x:/prj/tech/libsrc/prof/RCS/makefile 1.8 1995/10/06 13:38:55 buzzard Exp $
# $Log: makefile $
# Revision 1.8  1995/10/06  13:38:55  buzzard
# new build system somehow didn't get checked in?
# 

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = prof

prof_OBJS = prof

prof_HDRS = prof.h

%include $(MRC)\make.rc
