head	 2.2;
branch   ;
access   ;
symbols  SHIPPED_F95:2.1 oldnmk:1.30.1 FLT_SHIP:1.30.1.1;
locks    ; strict;
comment  @# @;


2.2
date	 1996.04.08.16.55.28;  author TOML;  state Exp;
branches ;
next	 2.1;

2.1
date	 1995.10.18.12.30.51;  author ept;  state Exp;
branches ;
next	 1.30;

1.30
date	 1994.11.18.12.18.56;  author mahk;  state Exp;
branches 1.30.1.1;
next	 1.29;

1.29
date	 1994.10.13.16.20.35;  author xemu;  state Exp;
branches ;
next	 1.28;

1.28
date	 1994.07.09.20.04.14;  author mahk;  state Exp;
branches ;
next	 1.27;

1.27
date	 1994.07.09.18.56.31;  author mahk;  state Exp;
branches ;
next	 1.26;

1.26
date	 1994.03.21.20.31.13;  author kaboom;  state Exp;
branches ;
next	 1.25;

1.25
date	 1994.03.02.18.40.49;  author jak;  state Exp;
branches ;
next	 1.24;

1.24
date	 1994.02.07.16.15.27;  author mahk;  state Exp;
branches ;
next	 1.23;

1.23
date	 1993.12.16.08.03.01;  author kaboom;  state Exp;
branches ;
next	 1.22;

1.22
date	 1993.06.14.17.35.22;  author xemu;  state Exp;
branches ;
next	 1.21;

1.21
date	 1993.06.04.15.32.09;  author xemu;  state Exp;
branches ;
next	 1.20;

1.20
date	 1993.05.21.11.17.41;  author xemu;  state Exp;
branches ;
next	 1.19;

1.19
date	 1993.05.18.14.27.29;  author xemu;  state Exp;
branches ;
next	 1.18;

1.18
date	 1993.05.12.16.30.58;  author xemu;  state Exp;
branches ;
next	 1.17;

1.17
date	 1993.05.03.18.35.07;  author mahk;  state Exp;
branches ;
next	 1.16;

1.16
date	 1993.04.30.13.13.40;  author mahk;  state Exp;
branches ;
next	 1.15;

1.15
date	 1993.04.30.13.12.02;  author xemu;  state Exp;
branches ;
next	 1.14;

1.14
date	 1993.04.17.00.38.13;  author mahk;  state Exp;
branches ;
next	 1.13;

1.13
date	 1993.04.09.16.08.56;  author xemu;  state Exp;
branches ;
next	 1.12;

1.12
date	 1993.04.08.12.26.08;  author xemu;  state Exp;
branches ;
next	 1.11;

1.11
date	 1993.04.05.23.42.10;  author mahk;  state Exp;
branches ;
next	 1.10;

1.10
date	 1993.04.05.16.40.54;  author xemu;  state Exp;
branches ;
next	 1.9;

1.9
date	 1993.03.30.20.34.09;  author unknown;  state Exp;
branches ;
next	 1.8;

1.8
date	 1993.03.29.20.45.55;  author mahk;  state Exp;
branches ;
next	 1.7;

1.7
date	 1993.03.26.19.54.37;  author xemu;  state Exp;
branches ;
next	 1.6;

1.6
date	 1993.03.24.12.31.50;  author xemu;  state Exp;
branches ;
next	 1.5;

1.5
date	 1993.03.22.19.28.38;  author xemu;  state Exp;
branches ;
next	 1.4;

1.4
date	 1993.03.22.17.38.03;  author xemu;  state Exp;
branches ;
next	 1.3;

1.3
date	 1993.03.22.16.39.30;  author xemu;  state Exp;
branches ;
next	 1.2;

1.2
date	 1993.03.22.16.37.26;  author xemu;  state Exp;
branches ;
next	 1.1;

1.1
date	 1993.03.22.16.24.34;  author mahk;  state Exp;
branches ;
next	 ;

1.30.1.1
date	 1994.12.10.10.44.13;  author lmfeeney;  state Exp;
branches ;
next	 ;


desc
@This is doofy.  It will become cool. 
@


2.2
log
@*** empty log message ***
@
text
@#
# $Source: x:/prj/tech/libsrc/ui/RCS/makefile $
# $Revision: 2.1 $
# $Author: ept $
# $Date: 1995/10/18 12:30:51 $

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = ui

irrupt_OBJS = curdrw

ui_OBJS = butarray curdrw cursors event gadgets hotkey menu plain \
	pushbutt qboxgadg region slab slider textgadg texttool tng \
	tngbarry tngfont tngmenu tngplain tngpushb tngqbox tngslidr tngtextg \
	uires vmouse

ui_HDRS = butarray.h curdat.h cursors.h curtyp.h event.h gadgets.h hotkey.h menu.h \
	plain.h pushbutt.h qboxgadg.h region.h slab.h slider.h textgadg.h texttool.h \
	tng.h tngapp.h tngbarry.h tngmenu.h tngplain.h tngpushb.h tngqbox.h tngslidr.h \
	tngtextg.h uires.h vmouse.h


%include $(MRC)\make.rc

@


2.1
log
@This is the new makefile for the new make system.
@
text
@d2 4
a5 4
# $Source: t:/prj/tech/libsrc/ui/rcs/makefile $
# $Revision: 1.30.1.1 $
# $Author: lmfeeney $
# $Date: 1994/12/10 10:44:13 $
d9 1
a9 1
PROJECT = windex
@


1.30
log
@added uires
@
text
@d2 4
a5 4
# $Source: r:/prj/lib/src/ui/rcs/makefile $
# $Revision: 1.29 $
# $Author: xemu $
# $Date: 1994/10/13 16:20:35 $
d7 1
a7 4
DEBUG_ON = 1
SPEW_ON = 1
WARN_ON = 1
DBG_ON = 1
d9 1
a9 4
COMPILER = watcom
SRCDIR = r:\prj\lib\src\ui
RELDIR = r:\prj\lib\rel
BUILD_DIR = r:\prj\lib\build\ui
d11 1
a11 21
OBJDIR = obj
BINDIR =
LIBDIR = $(RELDIR)
INCDIR = $(RELDIR)
INCPATH = . $(SRCDIR) $(RELDIR)
LIBPATH = . $(RELDIR)
PROG_TARGETS = uitest
LIB_TARGETS =  ui
HDR_TARGETS =  
INST_TARGETS = ui
CURDRW.C_CFLAGS=-zu
UI_OBJS = gadgets.obj region.obj cursors.obj curdrw.obj event.obj slab.obj \
        pushbutt.obj butarray.obj qboxgadg.obj textgadg.obj slider.obj \
        texttool.obj tngfont.obj tng.obj  hotkey.obj\
        tngqbox.obj tngtextg.obj tngpushb.obj tngslidr.obj tngbarry.obj \
        plain.obj tngplain.obj menu.obj tngmenu.obj uires.obj vmouse.obj
UI_HDRS = gadgets.h region.h cursors.h event.h slab.h pushbutt.h \
        butarray.h qboxgadg.h textgadg.h slider.h texttool.h \
        tngqbox.h tngtextg.h tngpushb.h tngslidr.h tngbarry.h tng.h \
        tngapp.h hotkey.h plain.h tngplain.h menu.h tngmenu.h \
        curdat.h curtyp.h uires.h vmouse.h
d13 1
a13 3
UITEST_OBJS = uitest.obj
UITEST_LIBS = _lg.lib _2d.lib _input.lib _res.lib _fix.lib \
        _mprintf.lib _dstruct.lib ui.lib _fault.lib
d15 1
a15 1
!include $(INIT)/make.rc
d17 1
a17 1
### OPUS MKMF:  Do not remove this line!  Automatic dependencies follow.
d19 4
a22 5
butarray.obj objo\butarray.obj objd\butarray.obj: 2d.h 2dres.h array.h butarray.h ctype.h cursors.h datapath.h \
	 dbg.h dbgmacro.h error.h event.h fcntl.h fix.h gadgets.h io.h kb.h \
	 kbcook.h lg.h lgalt.h malloc.h memall.h memmacro.h mouse.h rect.h \
	 region.h res.h restypes.h slab.h slider.h slist.h stat.h stdio.h \
	 stdlib.h string.h tng.h tngapp.h tngbarry.h tngslidr.h types.h
d24 4
a27 5
curdrw.obj objo\curdrw.obj objd\curdrw.obj: 2d.h _2d.h _3d.h _babl2.h _dstruct.h _edms.h _lg.h _mouse.h \
	 _network.h _parse.h _res.h _sound.h _testlib.h _ui.h array.h \
	 curdat.h cursors.h curtyp.h dbg.h dbgmacro.h error.h fix.h lg.h \
	 lgalt.h libdbg.h malloc.h memall.h memmacro.h mouse.h rect.h \
	 region.h slab.h slist.h stdio.h stdlib.h string.h types.h
a28 5
cursors.obj objo\cursors.obj objd\cursors.obj: 2d.h _2d.h _3d.h _babl2.h _dstruct.h _edms.h _lg.h _mouse.h \
	 _network.h _parse.h _res.h _sound.h _testlib.h _ui.h array.h \
	 cursors.h curtyp.h dbg.h dbgmacro.h error.h fix.h lg.h lgalt.h \
	 libdbg.h malloc.h memall.h memmacro.h mouse.h rect.h region.h \
	 slab.h slist.h stdio.h stdlib.h string.h types.h vmouse.h
d30 1
a30 4
event.obj objo\event.obj objd\event.obj: 2d.h _ui.h array.h ctype.h cursors.h dbg.h dbgmacro.h error.h \
	 event.h fix.h kb.h kbcook.h lg.h lgalt.h malloc.h memall.h \
	 memmacro.h mouse.h rect.h region.h slab.h slist.h stdio.h stdlib.h \
	 types.h vmouse.h
a31 135
gadgets.obj objo\gadgets.obj objd\gadgets.obj: 2d.h 2dres.h _ui.h array.h ctype.h cursors.h datapath.h dbg.h \
	 dbgmacro.h error.h event.h fix.h gadgets.h kb.h kbcook.h lg.h \
	 lgalt.h lgsprntf.h malloc.h memall.h memmacro.h mouse.h rect.h \
	 region.h res.h restypes.h slab.h slist.h stdarg.h stdio.h stdlib.h \
	 string.h tng.h tngapp.h types.h

hotkey.obj objo\hotkey.obj objd\hotkey.obj: _dstruct.h _ui.h array.h ctype.h dbg.h dbgmacro.h error.h \
	 hash.h hotkey.h kb.h kbcook.h lg.h lgalt.h malloc.h memall.h \
	 memmacro.h stdio.h string.h types.h

hottest.obj objo\hottest.obj objd\hottest.obj: _dstruct.h array.h ctype.h dbg.h dbgmacro.h error.h hash.h \
	 hotkey.h kb.h kbcook.h lg.h lgalt.h malloc.h memall.h memmacro.h \
	 stdio.h stdlib.h types.h

menu.obj objo\menu.obj objd\menu.obj: 2d.h 2dres.h _dstruct.h _ui.h array.h ctype.h cursors.h \
	 datapath.h dbg.h dbgmacro.h error.h event.h fix.h gadgets.h hash.h \
	 hotkey.h kb.h kbcook.h lg.h lgalt.h llist.h malloc.h memall.h \
	 memmacro.h menu.h mouse.h rect.h region.h res.h restypes.h slab.h \
	 slist.h stdio.h stdlib.h string.h texttool.h tng.h tngapp.h \
	 tngmenu.h types.h

monofont.obj objo\monofont.obj objd\monofont.obj: mprintf.h rect.h string.h texttool.h

plain.obj objo\plain.obj objd\plain.obj: 2d.h 2dres.h _ui.h array.h cursors.h datapath.h dbg.h dbgmacro.h \
	 error.h event.h fix.h gadgets.h lg.h lgalt.h malloc.h memall.h \
	 memmacro.h mouse.h plain.h rect.h region.h res.h restypes.h slab.h \
	 slist.h stdio.h stdlib.h tng.h tngapp.h tngplain.h types.h

pushbutt.obj objo\pushbutt.obj objd\pushbutt.obj: 2d.h 2dres.h _ui.h array.h cursors.h datapath.h dbg.h \
	 dbgmacro.h error.h event.h fix.h gadgets.h lg.h lgalt.h malloc.h \
	 memall.h memmacro.h mouse.h pushbutt.h rect.h region.h res.h \
	 restypes.h slab.h slist.h stdio.h stdlib.h string.h tng.h tngapp.h \
	 tngpushb.h types.h

qboxgadg.obj objo\qboxgadg.obj objd\qboxgadg.obj: 2d.h 2dres.h _ui.h array.h ctype.h cursors.h datapath.h dbg.h \
	 dbgmacro.h error.h event.h fcntl.h fix.h gadgets.h io.h kb.h \
	 kbcook.h lg.h lgalt.h malloc.h memall.h memmacro.h mouse.h \
	 qboxgadg.h rect.h region.h res.h restypes.h slab.h slist.h stat.h \
	 stdio.h stdlib.h string.h tng.h tngapp.h tngqbox.h types.h

realfont.obj objo\realfont.obj objd\realfont.obj: 2d.h fakefont.h fcntl.h fix.h io.h mprintf.h rect.h stat.h \
	 stdlib.h string.h texttool.h types.h

region.obj objo\region.obj objd\region.obj: 2d.h 2dres.h _ui.h array.h cursors.h datapath.h dbg.h \
	 dbgmacro.h error.h event.h fix.h gadgets.h lg.h lgalt.h malloc.h \
	 memall.h memmacro.h mouse.h rect.h region.h res.h restypes.h \
	 slab.h slist.h stdio.h stdlib.h tng.h tngapp.h types.h

slab.obj objo\slab.obj objd\slab.obj: 2d.h array.h cursors.h dbg.h dbgmacro.h error.h fix.h lg.h \
	 lgalt.h malloc.h memall.h memmacro.h mouse.h rect.h region.h \
	 slab.h slist.h stdio.h types.h

slider.obj objo\slider.obj objd\slider.obj: 2d.h 2dres.h _ui.h array.h cursors.h datapath.h dbg.h \
	 dbgmacro.h error.h event.h fix.h gadgets.h lg.h lgalt.h malloc.h \
	 memall.h memmacro.h mouse.h rect.h region.h res.h restypes.h \
	 slab.h slider.h slist.h stdio.h stdlib.h string.h tng.h tngapp.h \
	 tngslidr.h types.h

textgadg.obj objo\textgadg.obj objd\textgadg.obj: 2d.h 2dres.h _ui.h array.h cursors.h datapath.h dbg.h \
	 dbgmacro.h error.h event.h fakefont.h fix.h gadgets.h lg.h lgalt.h \
	 malloc.h memall.h memmacro.h mouse.h rect.h region.h res.h \
	 restypes.h slab.h slider.h slist.h stdio.h stdlib.h string.h \
	 textgadg.h texttool.h tng.h tngapp.h tngslidr.h tngtextg.h types.h

texttool.obj objo\texttool.obj objd\texttool.obj: ctype.h dbg.h dbgmacro.h fakefont.h lg.h lgalt.h malloc.h \
	 memall.h memmacro.h mprintf.h rect.h stdio.h string.h texttool.h \
	 tngfont.h types.h

tng.obj objo\tng.obj objd\tng.obj: 2d.h 2dres.h _ui.h datapath.h dbg.h dbgmacro.h error.h fix.h \
	 gadgets.h lg.h lgalt.h malloc.h memall.h memmacro.h rect.h \
	 region.h res.h restypes.h slist.h stdio.h stdlib.h tng.h tngapp.h \
	 types.h

tngbarry.obj objo\tngbarry.obj objd\tngbarry.obj: 2d.h 2dres.h _ui.h barrykey.h ctype.h datapath.h dbg.h \
	 dbgmacro.h error.h fcntl.h fix.h gadgets.h io.h kb.h kbcook.h \
	 keydefs.h lg.h lgalt.h malloc.h memall.h memmacro.h mprintf.h \
	 rect.h region.h res.h restypes.h slist.h stat.h stdio.h stdlib.h \
	 tng.h tngapp.h tngbarry.h tngslidr.h types.h

tngfont.obj objo\tngfont.obj objd\tngfont.obj: 2d.h 2dres.h datapath.h dbg.h dbgmacro.h error.h fakefont.h \
	 fcntl.h fix.h gadgets.h io.h lg.h lgalt.h malloc.h memall.h \
	 memmacro.h mprintf.h rect.h region.h res.h restypes.h slist.h \
	 stat.h stdio.h stdlib.h string.h texttool.h tng.h tngapp.h \
	 tngfont.h types.h

tngmenu.obj objo\tngmenu.obj objd\tngmenu.obj: 2d.h 2dres.h _dstruct.h _ui.h array.h barrykey.h ctype.h \
	 datapath.h dbg.h dbgmacro.h error.h fix.h gadgets.h hash.h \
	 hotkey.h kb.h kbcook.h keydefs.h lg.h lgalt.h llist.h malloc.h \
	 memall.h memmacro.h rect.h region.h res.h restypes.h slist.h \
	 stdio.h stdlib.h string.h texttool.h tng.h tngapp.h tngfont.h \
	 tngmenu.h types.h

tngplain.obj objo\tngplain.obj objd\tngplain.obj: 2d.h 2dres.h _ui.h datapath.h dbg.h dbgmacro.h error.h fix.h \
	 gadgets.h lg.h lgalt.h malloc.h memall.h memmacro.h rect.h \
	 region.h res.h restypes.h slist.h stdio.h stdlib.h tng.h tngapp.h \
	 tngplain.h types.h

tngpushb.obj objo\tngpushb.obj objd\tngpushb.obj: 2d.h 2dres.h _ui.h datapath.h dbg.h dbgmacro.h error.h \
	 fcntl.h fix.h gadgets.h io.h lg.h lgalt.h malloc.h memall.h \
	 memmacro.h rect.h region.h res.h restypes.h slist.h stat.h stdio.h \
	 stdlib.h tng.h tngapp.h tngpushb.h types.h

tngqbox.obj objo\tngqbox.obj objd\tngqbox.obj: 2d.h 2dres.h _ui.h ctype.h datapath.h dbg.h dbgmacro.h error.h \
	 fcntl.h fix.h gadgets.h io.h lg.h lgalt.h malloc.h math.h memall.h \
	 memmacro.h rect.h region.h res.h restypes.h slist.h stat.h stdio.h \
	 stdlib.h string.h texttool.h tng.h tngapp.h tngqbox.h tngslidr.h \
	 tngtextg.h types.h

tngslidr.obj objo\tngslidr.obj objd\tngslidr.obj: 2d.h 2dres.h _ui.h datapath.h dbg.h dbgmacro.h error.h fix.h \
	 gadgets.h lg.h lgalt.h malloc.h memall.h memmacro.h rect.h \
	 region.h res.h restypes.h slist.h stdio.h stdlib.h tng.h tngapp.h \
	 tngslidr.h types.h

tngtextg.obj objo\tngtextg.obj objd\tngtextg.obj: 2d.h 2dres.h _ui.h datapath.h dbg.h dbgmacro.h error.h \
	 fakefont.h fcntl.h fix.h gadgets.h io.h lg.h lgalt.h malloc.h \
	 memall.h memmacro.h rect.h region.h res.h restypes.h slist.h \
	 stat.h stdio.h stdlib.h texttool.h tng.h tngapp.h tngfont.h \
	 tngslidr.h tngtextg.h types.h

uires.obj objo\uires.obj objd\uires.obj: 2d.h 2dres.h cursors.h datapath.h dbg.h dbgmacro.h error.h fix.h \
	 lg.h lgalt.h malloc.h memall.h memmacro.h mouse.h rect.h region.h \
	 res.h restypes.h slist.h stdio.h stdlib.h string.h types.h uires.h

uitest.obj objo\uitest.obj objd\uitest.obj: 2d.h 2dres.h _dstruct.h array.h butarray.h ctype.h cursors.h \
	 datapath.h dbg.h dbgmacro.h error.h event.h fault.h fix.h \
	 gadgets.h hash.h hotkey.h io.h kb.h kbcook.h keydefs.h lg.h \
	 lgalt.h malloc.h memall.h memmacro.h menu.h mouse.h mprintf.h \
	 plain.h pushbutt.h qboxgadg.h r:\prj\lib\src\ui\data\gamescr.h \
	 rect.h region.h res.h restypes.h slab.h slider.h slist.h stat.h \
	 stdio.h stdlib.h string.h textgadg.h texttool.h tng.h tngapp.h \
	 tngbarry.h tngplain.h tngpushb.h tngqbox.h tngslidr.h tngtextg.h \
	 types.h

vmouse.obj objo\vmouse.obj objd\vmouse.obj: dbg.h dbgmacro.h error.h lg.h lgalt.h malloc.h memall.h \
	 memmacro.h mouse.h mprintf.h stdio.h types.h
@


1.30.1.1
log
@new make regime
@
text
@d7 4
a10 1
MAKETOP = $(CWD)
d12 4
a15 1
PROJECT = windex
d17 21
a37 1
%include $(MRC)\env.rc
d39 3
a41 1
%include $(MRC)\init.rc
d43 1
a43 1
LIBTARGS = ui
d45 1
a45 1
irrupt_OBJS = curdrw
d47 5
a51 4
ui_OBJS = butarray curdrw cursors event gadgets hotkey menu plain \
	pushbutt qboxgadg region slab slider textgadg texttool tng \
	tngbarry tngfont tngmenu tngplain tngpushb tngqbox tngslidr tngtextg \
	uires vmouse
d53 5
a57 4
ui_HDRS = butarray.h curdat.h cursors.h curtyp.h event.h gadgets.h hotkey.h menu.h \
	plain.h pushbutt.h qboxgadg.h region.h slab.h slider.h textgadg.h texttool.h \
	tng.h tngapp.h tngbarry.h tngmenu.h tngplain.h tngpushb.h tngqbox.h tngslidr.h \
	tngtextg.h uires.h vmouse.h
d59 5
d65 4
a68 1
%include $(MRC)\make.rc
d70 135
@



1.29
log
@vmouse!
@
text
@d3 3
a5 3
# $Revision: 1.28 $
# $Author: mahk $
# $Date: 1994/07/09 20:04:14 $
d32 1
a32 1
        plain.obj tngplain.obj menu.obj tngmenu.obj vmouse.obj
d37 1
a37 1
        curdat.h curtyp.h vmouse.h
d189 4
d194 2
a195 2
	 data\gamescr.h datapath.h dbg.h dbgmacro.h error.h event.h fault.h \
	 fix.h gadgets.h hash.h hotkey.h io.h kb.h kbcook.h keydefs.h lg.h \
d197 5
a201 4
	 plain.h pushbutt.h qboxgadg.h rect.h region.h res.h restypes.h \
	 slab.h slider.h slist.h stat.h stdio.h stdlib.h string.h \
	 textgadg.h texttool.h tng.h tngapp.h tngbarry.h tngplain.h \
	 tngpushb.h tngqbox.h tngslidr.h tngtextg.h types.h
@



1.28
log
@Changed release to rel
@
text
@d3 1
a3 1
# $Revision: 1.27 $
d5 1
a5 1
# $Date: 1994/07/09 18:56:31 $
d32 1
a32 1
        plain.obj tngplain.obj menu.obj tngmenu.obj
d37 1
a37 1
        curdat.h curtyp.h
d63 1
a63 1
	 slab.h slist.h stdio.h stdlib.h string.h types.h
d68 1
a68 1
	 types.h
d72 3
a74 3
	 lgalt.h malloc.h memall.h memmacro.h mouse.h rect.h region.h res.h \
	 restypes.h slab.h slist.h stdio.h stdlib.h string.h tng.h tngapp.h \
	 types.h
d197 3
@



1.27
log
@r:/ification.
@
text
@d3 3
a5 3
# $Revision: 1.26 $
# $Author: kaboom $
# $Date: 1994/03/21 20:31:13 $
d14 1
a14 1
RELDIR = r:\prj\lib\release
@



1.26
log
@depend.
@
text
@d2 4
a5 4
# $Source: n:/project/lib/src/ui/rcs/makefile $
# $Revision: 1.25 $
# $Author: jak $
# $Date: 1994/03/02 18:40:49 $
d13 3
a15 3
SRCDIR = n:\project\lib\src\ui
RELDIR = n:\project\lib\release
BUILD_DIR = n:\project\lib\build\ui
@



1.25
log
@Added fault library.
@
text
@d3 3
a5 3
# $Revision: 1.24 $
# $Author: mahk $
# $Date: 1994/02/07 16:15:27 $
d47 1
a47 1
butarray.obj: 2d.h 2dres.h array.h butarray.h ctype.h cursors.h datapath.h \
d53 1
a53 1
curdrw.obj: 2d.h _2d.h _3d.h _babl2.h _dstruct.h _edms.h _lg.h _mouse.h \
d59 1
a59 1
cursors.obj: 2d.h _2d.h _3d.h _babl2.h _dstruct.h _edms.h _lg.h _mouse.h \
d65 1
a65 1
event.obj: 2d.h _ui.h array.h ctype.h cursors.h dbg.h dbgmacro.h error.h \
d70 1
a70 1
gadgets.obj: 2d.h 2dres.h _ui.h array.h ctype.h cursors.h datapath.h dbg.h \
d76 1
a76 1
hotkey.obj: _dstruct.h _ui.h array.h ctype.h dbg.h dbgmacro.h error.h \
d80 1
a80 1
hottest.obj: _dstruct.h array.h ctype.h dbg.h dbgmacro.h error.h hash.h \
d84 1
a84 1
menu.obj: 2d.h 2dres.h _dstruct.h _ui.h array.h ctype.h cursors.h \
d91 1
a91 1
monofont.obj: mprintf.h rect.h string.h texttool.h
d93 1
a93 1
plain.obj: 2d.h 2dres.h _ui.h array.h cursors.h datapath.h dbg.h dbgmacro.h \
d98 1
a98 1
pushbutt.obj: 2d.h 2dres.h _ui.h array.h cursors.h datapath.h dbg.h \
d104 1
a104 1
qboxgadg.obj: 2d.h 2dres.h _ui.h array.h ctype.h cursors.h datapath.h dbg.h \
d110 1
a110 1
realfont.obj: 2d.h fakefont.h fcntl.h fix.h io.h mprintf.h rect.h stat.h \
d113 1
a113 1
region.obj: 2d.h 2dres.h _ui.h array.h cursors.h datapath.h dbg.h \
d118 1
a118 1
slab.obj: 2d.h array.h cursors.h dbg.h dbgmacro.h error.h fix.h lg.h \
d122 1
a122 1
slider.obj: 2d.h 2dres.h _ui.h array.h cursors.h datapath.h dbg.h \
d128 1
a128 1
textgadg.obj: 2d.h 2dres.h _ui.h array.h cursors.h datapath.h dbg.h \
d134 1
a134 1
texttool.obj: ctype.h dbg.h dbgmacro.h fakefont.h lg.h lgalt.h malloc.h \
d138 1
a138 1
tng.obj: 2d.h 2dres.h _ui.h datapath.h dbg.h dbgmacro.h error.h fix.h \
d143 1
a143 1
tngbarry.obj: 2d.h 2dres.h _ui.h barrykey.h ctype.h datapath.h dbg.h \
d149 1
a149 1
tngfont.obj: 2d.h 2dres.h datapath.h dbg.h dbgmacro.h error.h fakefont.h \
d155 1
a155 1
tngmenu.obj: 2d.h 2dres.h _dstruct.h _ui.h array.h barrykey.h ctype.h \
d162 1
a162 1
tngplain.obj: 2d.h 2dres.h _ui.h datapath.h dbg.h dbgmacro.h error.h fix.h \
d167 1
a167 1
tngpushb.obj: 2d.h 2dres.h _ui.h datapath.h dbg.h dbgmacro.h error.h \
d172 1
a172 1
tngqbox.obj: 2d.h 2dres.h _ui.h ctype.h datapath.h dbg.h dbgmacro.h error.h \
d178 1
a178 1
tngslidr.obj: 2d.h 2dres.h _ui.h datapath.h dbg.h dbgmacro.h error.h fix.h \
d183 1
a183 1
tngtextg.obj: 2d.h 2dres.h _ui.h datapath.h dbg.h dbgmacro.h error.h \
d189 1
a189 1
uitest.obj: 2d.h 2dres.h _dstruct.h array.h butarray.h ctype.h cursors.h \
@



1.24
log
@Added install headers.
@
text
@d3 3
a5 3
# $Revision: 1.23 $
# $Author: kaboom $
# $Date: 1993/12/16 08:03:01 $
d41 1
a41 1
        _mprintf.lib _dstruct.lib ui.lib
d190 2
a191 2
	 data\gamescr.h datapath.h dbg.h dbgmacro.h error.h event.h fix.h \
	 gadgets.h hash.h hotkey.h io.h kb.h kbcook.h keydefs.h lg.h \
@



1.23
log
@Added curdrw.obj.
@
text
@d2 4
a5 4
# $Source$
# $Revision$
# $Author$
# $Date$
d36 2
a37 1
        tngapp.h hotkey.h plain.h tngplain.h menu.h tngmenu.h
@



1.22
log
@did a depend
@
text
@d1 6
a11 1

d15 1
a15 1
BUILD_DIR = N:\project\lib\build\ui
d27 2
a28 2

UI_OBJS = gadgets.obj region.obj cursors.obj event.obj slab.obj \
a36 1
UI_LIBS = 
a41 1

d48 3
a50 4
	 kbcook.h lg.h lgalt.h libdbg.h malloc.h memall.h memmacro.h \
	 mouse.h rect.h region.h res.h restypes.h slab.h slider.h slist.h \
	 stat.h stdio.h stdlib.h string.h tng.h tngapp.h tngbarry.h \
	 tngslidr.h types.h
d52 3
a54 1
cursors.obj: 2d.h array.h cursors.h dbg.h dbgmacro.h error.h fix.h lg.h \
d58 5
a62 3
event.obj: 2d.h array.h ctype.h cursors.h dbg.h dbgmacro.h error.h event.h \
	 fix.h kb.h kbcook.h lg.h lgalt.h libdbg.h malloc.h memall.h \
	 memmacro.h mouse.h rect.h region.h slab.h slist.h stdio.h types.h
d64 6
a69 1
gadgets.obj: 2d.h 2dres.h array.h ctype.h cursors.h datapath.h dbg.h \
d71 2
a72 11
	 lgalt.h libdbg.h malloc.h memall.h memmacro.h mouse.h rect.h \
	 region.h res.h restypes.h slab.h slist.h stdio.h stdlib.h string.h \
	 tng.h tngapp.h types.h

gadtest.obj: 2d.h 2dres.h array.h bugtrak.h butarray.h ctype.h cursors.h \
	 data\resgadg.h datapath.h dbg.h dbgmacro.h error.h event.h fix.h \
	 gadgets.h io.h kb.h kbcook.h lg.h lgalt.h libdbg.h malloc.h \
	 memall.h memmacro.h mouse.h mprintf.h projdbg.h pushbutt.h \
	 qboxgadg.h rect.h region.h res.h restypes.h slab.h slider.h \
	 slist.h stat.h stdio.h stdlib.h textgadg.h texttool.h tng.h \
	 tngapp.h tngbarry.h tngpushb.h tngqbox.h tngslidr.h tngtextg.h \
d75 3
a77 3
hotkey.obj: array.h ctype.h dbg.h dbgmacro.h error.h hash.h hotkey.h kb.h \
	 kbcook.h lg.h lgalt.h libdbg.h malloc.h memall.h memmacro.h \
	 stdio.h string.h types.h
d79 3
a81 3
hottest.obj: ctype.h dbg.h dbgmacro.h error.h hash.h hotkey.h kb.h kbcook.h \
	 lg.h lgalt.h libdbg.h malloc.h memall.h memmacro.h stdio.h \
	 stdlib.h types.h
d83 3
a85 3
menu.obj: 2d.h 2dres.h array.h ctype.h cursors.h datapath.h dbg.h \
	 dbgmacro.h error.h event.h fix.h gadgets.h hash.h hotkey.h kb.h \
	 kbcook.h lg.h lgalt.h libdbg.h llist.h malloc.h memall.h \
d92 4
a95 5
plain.obj: 2d.h 2dres.h array.h cursors.h datapath.h dbg.h dbgmacro.h \
	 error.h event.h fix.h gadgets.h lg.h lgalt.h libdbg.h malloc.h \
	 memall.h memmacro.h mouse.h plain.h rect.h region.h res.h \
	 restypes.h slab.h slist.h stdio.h stdlib.h tng.h tngapp.h \
	 tngplain.h types.h
d97 2
a98 2
pushbutt.obj: 2d.h 2dres.h array.h cursors.h datapath.h dbg.h dbgmacro.h \
	 error.h event.h fix.h gadgets.h lg.h lgalt.h libdbg.h malloc.h \
d100 1
a100 1
	 restypes.h slab.h slist.h stdio.h stdlib.h tng.h tngapp.h \
d103 1
a103 1
qboxgadg.obj: 2d.h 2dres.h array.h ctype.h cursors.h datapath.h dbg.h \
d105 3
a107 3
	 kbcook.h lg.h lgalt.h libdbg.h malloc.h memall.h memmacro.h \
	 mouse.h qboxgadg.h rect.h region.h res.h restypes.h slab.h slist.h \
	 stat.h stdio.h stdlib.h string.h tng.h tngapp.h tngqbox.h types.h
d112 4
a115 4
region.obj: 2d.h 2dres.h array.h cursors.h datapath.h dbg.h dbgmacro.h \
	 error.h event.h fix.h gadgets.h lg.h lgalt.h libdbg.h malloc.h \
	 memall.h memmacro.h mouse.h mprintf.h rect.h region.h res.h \
	 restypes.h slab.h slist.h stdio.h stdlib.h tng.h tngapp.h types.h
d118 2
a119 2
	 lgalt.h libdbg.h malloc.h memall.h memmacro.h mouse.h rect.h \
	 region.h slab.h slist.h stdio.h types.h
d121 2
a122 2
slider.obj: 2d.h 2dres.h array.h cursors.h datapath.h dbg.h dbgmacro.h \
	 error.h event.h fix.h gadgets.h lg.h lgalt.h libdbg.h malloc.h \
d127 2
a128 2
textgadg.obj: 2d.h 2dres.h array.h cursors.h datapath.h dbg.h dbgmacro.h \
	 error.h event.h fakefont.h fix.h gadgets.h lg.h lgalt.h libdbg.h \
d133 3
a135 7
texttest.obj: 2d.h 2dres.h array.h ctype.h cursors.h data\resgadg.h \
	 datapath.h dbg.h dbgmacro.h error.h event.h fix.h gadgets.h io.h \
	 kb.h kbcook.h lg.h lgalt.h libdbg.h malloc.h memall.h memmacro.h \
	 mouse.h mprintf.h projdbg.h pushbutt.h rect.h region.h res.h \
	 restypes.h slab.h slider.h slist.h stat.h stdio.h stdlib.h \
	 textgadg.h texttool.h tng.h tngapp.h tngpushb.h tngslidr.h \
	 tngtextg.h types.h
d137 4
a140 3
texttool.obj: ctype.h dbg.h dbgmacro.h fakefont.h lg.h lgalt.h libdbg.h \
	 malloc.h memall.h memmacro.h mprintf.h rect.h stdio.h string.h \
	 texttool.h tngfont.h types.h
d142 5
a146 3
tng.obj: 2d.h 2dres.h datapath.h dbg.h dbgmacro.h error.h fix.h gadgets.h \
	 lg.h lgalt.h libdbg.h malloc.h memall.h memmacro.h rect.h res.h \
	 restypes.h stdio.h stdlib.h tng.h tngapp.h types.h
d148 5
a152 4
tngbarry.obj: 2d.h 2dres.h datapath.h dbg.h dbgmacro.h error.h fcntl.h \
	 fix.h gadgets.h io.h lg.h lgalt.h libdbg.h malloc.h memall.h \
	 memmacro.h rect.h res.h restypes.h stat.h stdio.h stdlib.h tng.h \
	 tngapp.h tngbarry.h tngslidr.h types.h
d154 4
a157 3
tngfont.obj: 2d.h 2dres.h datapath.h dbg.h dbgmacro.h error.h fakefont.h \
	 fcntl.h fix.h gadgets.h io.h lg.h lgalt.h libdbg.h malloc.h \
	 memall.h memmacro.h mprintf.h rect.h res.h restypes.h stat.h \
d159 1
a159 1
	 types.h
d161 4
a164 5
tngmenu.obj: 2d.h 2dres.h ctype.h datapath.h dbg.h dbgmacro.h error.h fix.h \
	 gadgets.h hash.h hotkey.h kb.h kbcook.h keydefs.h lg.h lgalt.h \
	 libdbg.h llist.h malloc.h memall.h memmacro.h rect.h res.h \
	 restypes.h stdio.h stdlib.h string.h texttool.h tng.h tngapp.h \
	 tngfont.h tngmenu.h types.h
d166 4
a169 4
tngplain.obj: 2d.h 2dres.h datapath.h dbg.h dbgmacro.h error.h fix.h \
	 gadgets.h lg.h lgalt.h libdbg.h malloc.h memall.h memmacro.h \
	 rect.h res.h restypes.h stdio.h stdlib.h tng.h tngapp.h tngplain.h \
	 types.h
d171 5
a175 4
tngpushb.obj: 2d.h 2dres.h datapath.h dbg.h dbgmacro.h error.h fcntl.h \
	 fix.h gadgets.h io.h lg.h lgalt.h libdbg.h malloc.h memall.h \
	 memmacro.h rect.h res.h restypes.h stat.h stdio.h stdlib.h tng.h \
	 tngapp.h tngpushb.h types.h
d177 4
a180 4
tngqbox.obj: 2d.h 2dres.h datapath.h dbg.h dbgmacro.h error.h fcntl.h fix.h \
	 gadgets.h io.h lg.h lgalt.h libdbg.h malloc.h memall.h memmacro.h \
	 rect.h res.h restypes.h stat.h stdio.h stdlib.h string.h \
	 texttool.h tng.h tngapp.h tngqbox.h tngslidr.h tngtextg.h types.h
d182 5
a186 4
tngslidr.obj: 2d.h 2dres.h datapath.h dbg.h dbgmacro.h error.h fix.h \
	 gadgets.h lg.h lgalt.h libdbg.h malloc.h memall.h memmacro.h \
	 rect.h res.h restypes.h stdio.h stdlib.h tng.h tngapp.h tngslidr.h \
	 types.h
d188 7
a194 6
tngtest.obj: 2d.h 2dres.h array.h bugtrak.h butarray.h ctype.h cursors.h \
	 datapath.h dbg.h dbgmacro.h error.h event.h fix.h gadgets.h io.h \
	 kb.h kbcook.h lg.h lgalt.h libdbg.h malloc.h memall.h memmacro.h \
	 mouse.h mprintf.h pushbutt.h qboxgadg.h rect.h region.h res.h \
	 resgadg.h restypes.h slab.h slider.h slist.h stat.h stdio.h \
	 stdlib.h textgadg.h texttool.h tng.h tngapp.h tngbarry.h \
a195 23

tngtextg.obj: 2d.h 2dres.h datapath.h dbg.h dbgmacro.h error.h fakefont.h \
	 fcntl.h fix.h gadgets.h io.h lg.h lgalt.h libdbg.h malloc.h \
	 memall.h memmacro.h rect.h res.h restypes.h stat.h stdio.h \
	 stdlib.h texttool.h tng.h tngapp.h tngfont.h tngslidr.h tngtextg.h \
	 types.h

uitest.obj: 2d.h 2dres.h array.h bugtrak.h butarray.h ctype.h cursors.h \
	 data\resgadg.h datapath.h dbg.h dbgmacro.h error.h event.h fix.h \
	 gadgets.h hash.h hotkey.h io.h kb.h kbcook.h keydefs.h lg.h \
	 lgalt.h libdbg.h malloc.h memall.h memmacro.h menu.h mouse.h \
	 mprintf.h plain.h projdbg.h pushbutt.h qboxgadg.h rect.h region.h \
	 res.h restypes.h slab.h slider.h slist.h stat.h stdio.h stdlib.h \
	 string.h textgadg.h texttool.h tng.h tngapp.h tngbarry.h \
	 tngplain.h tngpushb.h tngqbox.h tngslidr.h tngtextg.h types.h

workgadg.obj: 2d.h 2dres.h array.h bugtrak.h butarray.h cursors.h \
	 data\resgadg.h datapath.h dbg.h dbgmacro.h error.h event.h fix.h \
	 gadgets.h lg.h lgalt.h libdbg.h malloc.h memall.h memmacro.h \
	 mouse.h mprintf.h pushbutt.h qboxgadg.h rect.h region.h res.h \
	 restypes.h slab.h slider.h slist.h stdio.h stdlib.h textgadg.h \
	 texttool.h tng.h tngapp.h tngbarry.h tngpushb.h tngqbox.h \
	 tngslidr.h tngtextg.h types.h
@



1.21
log
@non-gfx depend
@
text
@d66 1
a66 1
	 gadgets.h gfx.h io.h kb.h kbcook.h lg.h lgalt.h libdbg.h malloc.h \
d133 4
a136 4
	 datapath.h dbg.h dbgmacro.h error.h event.h fix.h gadgets.h gfx.h \
	 io.h kb.h kbcook.h lg.h lgalt.h libdbg.h malloc.h memall.h \
	 memmacro.h mouse.h mprintf.h projdbg.h pushbutt.h rect.h region.h \
	 res.h restypes.h slab.h slider.h slist.h stat.h stdio.h stdlib.h \
d186 4
a189 4
	 datapath.h dbg.h dbgmacro.h error.h event.h fix.h gadgets.h gfx.h \
	 io.h kb.h kbcook.h lg.h lgalt.h libdbg.h malloc.h memall.h \
	 memmacro.h mouse.h mprintf.h pushbutt.h qboxgadg.h rect.h region.h \
	 res.h resgadg.h restypes.h slab.h slider.h slist.h stat.h stdio.h \
d201 1
a201 1
	 gadgets.h gfx.h hash.h hotkey.h io.h kb.h kbcook.h keydefs.h lg.h \
@



1.20
log
@dependencies...
@
text
@d43 6
a48 5
butarray.obj: 2d.h array.h butarray.h ctype.h cursors.h datapath.h dbg.h \
	 error.h event.h fcntl.h fix.h gadgets.h gfx.h io.h kb.h kbcook.h \
	 lg.h lgalt.h libdbg.h malloc.h memall.h mouse.h rect.h region.h \
	 res.h restypes.h slab.h slider.h slist.h stat.h stdio.h stdlib.h \
	 string.h tng.h tngapp.h tngbarry.h tngslidr.h types.h
d50 3
a52 3
cursors.obj: 2d.h array.h cursors.h dbg.h error.h fix.h lg.h lgalt.h \
	 libdbg.h malloc.h memall.h mouse.h rect.h region.h slab.h slist.h \
	 stdio.h string.h types.h
d54 3
a56 3
event.obj: 2d.h array.h ctype.h cursors.h dbg.h error.h event.h fix.h kb.h \
	 kbcook.h lg.h lgalt.h libdbg.h malloc.h memall.h mouse.h rect.h \
	 region.h slab.h slist.h stdio.h types.h
d58 5
a62 4
gadgets.obj: 2d.h array.h ctype.h cursors.h datapath.h dbg.h error.h \
	 event.h fix.h gadgets.h gfx.h kb.h kbcook.h lg.h lgalt.h libdbg.h \
	 malloc.h memall.h mouse.h rect.h region.h res.h restypes.h slab.h \
	 slist.h stdio.h stdlib.h string.h tng.h tngapp.h types.h
d64 8
a71 7
gadtest.obj: 2d.h array.h bugtrak.h butarray.h ctype.h cursors.h \
	 resgadg.h datapath.h dbg.h error.h event.h fix.h gadgets.h \
	 gfx.h io.h kb.h kbcook.h lg.h lgalt.h libdbg.h malloc.h memall.h \
	 mouse.h mprintf.h pushbutt.h qboxgadg.h rect.h region.h res.h \
	 restypes.h slab.h slider.h slist.h stat.h stdio.h stdlib.h \
	 textgadg.h texttool.h tng.h tngapp.h tngbarry.h tngpushb.h \
	 tngqbox.h tngslidr.h tngtextg.h types.h
d73 3
a75 2
hotkey.obj: array.h ctype.h dbg.h error.h hash.h hotkey.h kb.h kbcook.h \
	 lg.h lgalt.h libdbg.h malloc.h memall.h stdio.h string.h types.h
d77 3
a79 2
hottest.obj: ctype.h dbg.h error.h hash.h hotkey.h kb.h kbcook.h lg.h \
	 lgalt.h libdbg.h malloc.h memall.h stdio.h stdlib.h types.h
d81 6
a86 5
menu.obj: 2d.h array.h ctype.h cursors.h datapath.h dbg.h error.h event.h \
	 fix.h gadgets.h gfx.h hash.h hotkey.h kb.h kbcook.h lg.h lgalt.h \
	 libdbg.h llist.h malloc.h memall.h menu.h mouse.h rect.h region.h \
	 res.h restypes.h slab.h slist.h stdio.h stdlib.h string.h \
	 texttool.h tng.h tngapp.h tngmenu.h types.h
d90 5
a94 4
plain.obj: 2d.h array.h cursors.h datapath.h dbg.h error.h event.h fix.h \
	 gadgets.h gfx.h lg.h lgalt.h libdbg.h malloc.h memall.h mouse.h \
	 plain.h rect.h region.h res.h restypes.h slab.h slist.h stdio.h \
	 stdlib.h tng.h tngapp.h tngplain.h types.h
d96 5
a100 4
pushbutt.obj: 2d.h array.h cursors.h datapath.h dbg.h error.h event.h fix.h \
	 gadgets.h gfx.h lg.h lgalt.h libdbg.h malloc.h memall.h mouse.h \
	 pushbutt.h rect.h region.h res.h restypes.h slab.h slist.h stdio.h \
	 stdlib.h tng.h tngapp.h tngpushb.h types.h
d102 5
a106 5
qboxgadg.obj: 2d.h array.h ctype.h cursors.h datapath.h dbg.h error.h \
	 event.h fcntl.h fix.h gadgets.h gfx.h io.h kb.h kbcook.h lg.h \
	 lgalt.h libdbg.h malloc.h memall.h mouse.h qboxgadg.h rect.h \
	 region.h res.h restypes.h slab.h slist.h stat.h stdio.h stdlib.h \
	 string.h tng.h tngapp.h tngqbox.h types.h
d111 4
a114 4
region.obj: 2d.h array.h cursors.h datapath.h dbg.h error.h event.h fix.h \
	 gadgets.h gfx.h lg.h lgalt.h libdbg.h malloc.h memall.h mouse.h \
	 mprintf.h rect.h region.h res.h restypes.h slab.h slist.h stdio.h \
	 stdlib.h tng.h tngapp.h types.h
d116 3
a118 3
slab.obj: 2d.h array.h cursors.h dbg.h error.h fix.h lg.h lgalt.h libdbg.h \
	 malloc.h memall.h mouse.h rect.h region.h slab.h slist.h stdio.h \
	 types.h
d120 5
a124 4
slider.obj: 2d.h array.h cursors.h datapath.h dbg.h error.h event.h fix.h \
	 gadgets.h gfx.h lg.h lgalt.h libdbg.h malloc.h memall.h mouse.h \
	 rect.h region.h res.h restypes.h slab.h slider.h slist.h stdio.h \
	 stdlib.h string.h tng.h tngapp.h tngslidr.h types.h
d126 5
a130 5
textgadg.obj: 2d.h array.h cursors.h datapath.h dbg.h error.h event.h \
	 fakefont.h fix.h gadgets.h gfx.h lg.h lgalt.h libdbg.h malloc.h \
	 memall.h mouse.h rect.h region.h res.h restypes.h slab.h slider.h \
	 slist.h stdio.h stdlib.h string.h textgadg.h texttool.h tng.h \
	 tngapp.h tngslidr.h tngtextg.h types.h
d132 7
a138 6
texttest.obj: 2d.h array.h ctype.h cursors.h resgadg.h datapath.h \
	 dbg.h error.h event.h fix.h gadgets.h gfx.h io.h kb.h kbcook.h \
	 lg.h lgalt.h libdbg.h malloc.h memall.h mouse.h mprintf.h \
	 pushbutt.h rect.h region.h res.h restypes.h slab.h slider.h \
	 slist.h stat.h stdio.h stdlib.h textgadg.h texttool.h tng.h \
	 tngapp.h tngpushb.h tngslidr.h tngtextg.h types.h
d140 17
a156 2
texttool.obj: ctype.h dbg.h fakefont.h lg.h lgalt.h libdbg.h malloc.h \
	 memall.h mprintf.h rect.h stdio.h string.h texttool.h tngfont.h \
d159 5
a163 3
tng.obj: 2d.h datapath.h dbg.h error.h fix.h gadgets.h gfx.h lg.h lgalt.h \
	 libdbg.h malloc.h memall.h rect.h res.h restypes.h stdio.h \
	 stdlib.h tng.h tngapp.h types.h
d165 4
a168 4
tngbarry.obj: 2d.h datapath.h dbg.h error.h fcntl.h fix.h gadgets.h gfx.h \
	 io.h lg.h lgalt.h libdbg.h malloc.h memall.h rect.h res.h \
	 restypes.h stat.h stdio.h stdlib.h tng.h tngapp.h tngbarry.h \
	 tngslidr.h types.h
d170 4
a173 4
tngfont.obj: 2d.h datapath.h dbg.h error.h fakefont.h fcntl.h fix.h \
	 gadgets.h gfx.h io.h lg.h lgalt.h libdbg.h malloc.h memall.h \
	 mprintf.h rect.h res.h restypes.h stat.h stdio.h stdlib.h string.h \
	 texttool.h tng.h tngapp.h tngfont.h types.h
d175 4
a178 4
tngmenu.obj: 2d.h ctype.h datapath.h dbg.h error.h fix.h gadgets.h gfx.h \
	 hash.h hotkey.h kb.h kbcook.h keydefs.h lg.h lgalt.h libdbg.h \
	 llist.h malloc.h memall.h rect.h res.h restypes.h stdio.h stdlib.h \
	 string.h texttool.h tng.h tngapp.h tngfont.h tngmenu.h types.h
d180 4
a183 3
tngplain.obj: 2d.h datapath.h dbg.h error.h fix.h gadgets.h gfx.h lg.h \
	 lgalt.h libdbg.h malloc.h memall.h rect.h res.h restypes.h stdio.h \
	 stdlib.h tng.h tngapp.h tngplain.h types.h
d185 12
a196 3
tngpushb.obj: 2d.h datapath.h dbg.h error.h fcntl.h fix.h gadgets.h gfx.h \
	 io.h lg.h lgalt.h libdbg.h malloc.h memall.h rect.h res.h \
	 restypes.h stat.h stdio.h stdlib.h tng.h tngapp.h tngpushb.h \
d199 8
a206 4
tngqbox.obj: 2d.h datapath.h dbg.h error.h fcntl.h fix.h gadgets.h gfx.h \
	 io.h lg.h lgalt.h libdbg.h malloc.h memall.h rect.h res.h \
	 restypes.h stat.h stdio.h stdlib.h string.h texttool.h tng.h \
	 tngapp.h tngqbox.h tngslidr.h tngtextg.h types.h
d208 5
a212 9
tngslidr.obj: 2d.h datapath.h dbg.h error.h fix.h gadgets.h gfx.h lg.h \
	 lgalt.h libdbg.h malloc.h memall.h rect.h res.h restypes.h stdio.h \
	 stdlib.h tng.h tngapp.h tngslidr.h types.h

tngtest.obj: 2d.h array.h bugtrak.h butarray.h ctype.h cursors.h datapath.h \
	 dbg.h error.h event.h fix.h gadgets.h gfx.h io.h kb.h kbcook.h \
	 lg.h lgalt.h libdbg.h malloc.h memall.h mouse.h mprintf.h \
	 pushbutt.h qboxgadg.h rect.h region.h res.h resgadg.h restypes.h \
	 slab.h slider.h slist.h stat.h stdio.h stdlib.h textgadg.h \
a214 21

tngtextg.obj: 2d.h datapath.h dbg.h error.h fakefont.h fcntl.h fix.h \
	 gadgets.h gfx.h io.h lg.h lgalt.h libdbg.h malloc.h memall.h \
	 rect.h res.h restypes.h stat.h stdio.h stdlib.h texttool.h tng.h \
	 tngapp.h tngfont.h tngslidr.h tngtextg.h types.h

uitest.obj: 2d.h array.h bugtrak.h butarray.h ctype.h cursors.h \
	 resgadg.h datapath.h dbg.h error.h event.h fix.h gadgets.h \
	 gfx.h hash.h hotkey.h io.h kb.h kbcook.h lg.h lgalt.h libdbg.h \
	 malloc.h memall.h menu.h mouse.h mprintf.h plain.h projdbg.h \
	 pushbutt.h qboxgadg.h rect.h region.h res.h restypes.h slab.h \
	 slider.h slist.h stat.h stdio.h stdlib.h string.h textgadg.h \
	 texttool.h tng.h tngapp.h tngbarry.h tngplain.h tngpushb.h \
	 tngqbox.h tngslidr.h tngtextg.h types.h

workgadg.obj: 2d.h array.h bugtrak.h butarray.h cursors.h resgadg.h \
	 datapath.h dbg.h error.h event.h fix.h gadgets.h gfx.h lg.h \
	 lgalt.h libdbg.h malloc.h memall.h mouse.h mprintf.h pushbutt.h \
	 qboxgadg.h rect.h region.h res.h restypes.h slab.h slider.h \
	 slist.h stdio.h stdlib.h textgadg.h texttool.h tng.h tngapp.h \
	 tngbarry.h tngpushb.h tngqbox.h tngslidr.h tngtextg.h types.h
@



1.19
log
@cleanup, added menus
@
text
@d43 156
@



1.18
log
@plain, tngplain
@
text
@d27 1
a27 1
        plain.obj tngplain.obj
d31 1
a31 1
        tngapp.h hotkey.h plain.h tngplain.h
d36 1
a36 1
        _mprintf.lib dstruct.lib ui.lib
@



1.17
log
@Ui library now includes hotkeys.
@
text
@d26 2
a27 1
        tngqbox.obj tngtextg.obj tngpushb.obj tngslidr.obj tngbarry.obj
d31 1
a31 1
        tngapp.h hotkey.h
@



1.16
log
@Array.h and array.obj are not included in this library anymore.
@
text
@d25 1
a25 1
        texttool.obj tngfont.obj tng.obj  \
d30 1
a30 1
        tngapp.h
@



1.15
log
@TNG stuff?
@
text
@d25 1
a25 1
        texttool.obj tngfont.obj tng.obj array.obj \
d30 1
a30 1
        tngapp.h array.h
@



1.14
log
@Here's a much simpler makefile that just makes ui.lib
@
text
@d1 4
d18 1
a18 1
PROG_TARGETS = 
d25 2
a26 1
        rect.obj texttool.obj realfont.obj monofont.obj
d28 3
a30 2
        butarray.h qboxgadg.h textgadg.h slider.h rect.h  \
        texttool.h 
d32 4
@



1.13
log
@ui
@
text
@a0 4
DEBUG_ON = 1
SPEW_ON = 1
WARN_ON = 1
DBG_ON = 1
a1 3
PROG_TARGETS =  regtest arraytst gadtest texttest workgadg testfont
LIB_TARGETS = ui
INST_TARGETS =
d3 4
a6 1
# The following are groups of objs, not really programs to be compiled
d8 10
a17 1
XEMU_OBJS = shodan.obj critai.obj physics.obj combat.obj mainui.obj
a18 30
MAHK_OBJS = manta.obj gamesys.obj bablstuf.obj grunge.obj

DC_OBJS = rend.obj world.obj editor.obj cspace.obj

# Here's the list for compiling whole programs

CITADEL_OBJS = main.obj init.obj $(XEMU_OBJS) $(DC_OBJS) $(MAHK_OBJS)
CITADEL_LIBS = $(LG_LIBS) 

REGTEST_OBJS = region.obj rect.obj test.obj
REGTEST_LIBS = lg.lib mprintf.lib

ARRAYTST_OBJS = array.obj arraytst.obj
ARRAYTST_LIBS = lg.lib mprintf.lib

GADTEST_OBJS = gadgets.obj rect.obj gadtest.obj region.obj event.obj \
        array.obj pushbutt.obj butarray.obj slider.obj slab.obj \
        qboxgadg.obj cursors.obj bugtrak.obj      
GADTEST_LIBS = _lg.lib _mprintf.lib _2d.lib _res.lib _kb.lib _mouse.lib

TEXTTEST_OBJS = texttest.obj gadgets.obj region.obj slider.obj \
        textgadg.obj rect.obj pushbutt.obj monofont.obj \
        event.obj array.obj cursors.obj slab.obj texttool.obj realfont.obj
TEXTTEST_LIBS = _2d.lib _res.lib _kb.lib _mouse.lib _mprintf.lib _lg.lib

WORKGADG_OBJS = workgadg.obj gadgets.obj region.obj cursors.obj slab.obj \
        bugtrak.obj qboxgadg.obj pushbutt.obj slider.obj butarray.obj \
        musicai.obj array.obj rect.obj textgadg.obj event.obj
WORKGADG_LIBS = _lg.lib _mprintf.lib _2d.lib _res.lib _kb.lib _mouse.lib

d21 1
a21 1
        rect.obj array.obj texttool.obj realfont.obj monofont.obj
d23 1
a23 1
        butarray.h qboxgadg.h textgadg.h slider.h rect.h array.h \
a26 2
TESTFONT_OBJS = testfont.obj 
TESTFONT_LIBS = 2d.lib mprintf.lib lg.lib
d28 1
a28 21
# Libraries

!if $(DEBUG_ON)
LG_LIBS	= _lg.lib _mprintf.lib _fix.lib _2d.lib _3d.lib _range.lib  _mouse.lib \
        _edms.lib  _res.lib
!else
LG_LIBS	= lg.lib mprintf.lib fix.lib 2d.lib 3d.lib range.lib mouse.lib \
        edms.lib res.lib
!endif

!include $(INIT)\make.rc

!if !defined(NONET)
# !include makefile.rcs
# !include inc/makefile.rcs
!endif

blah .PHONY:
        @@echo ROOTSRCDIR = $(ROOTSRCDIR)
        @@echo SRCDIR = $(SRCDIR)
        @@echo LIBPATH = $(LIBPATH)
@



1.12
log
@texttest support
@
text
@d6 1
a6 1
PROG_TARGETS =  regtest arraytst gadtest texttest workgadg
d35 3
a37 3
        textgadg.obj rect.obj pushbutt.obj \
        event.obj array.obj cursors.obj slab.obj
TEXTTEST_LIBS = lg.lib mprintf.lib 2d.lib res.lib kb.lib mouse.lib
d46 1
a46 1
        rect.obj array.obj
d48 2
a49 1
        butarray.h qboxgadg.h textgadg.h slider.h rect.h array.h
d52 3
a78 37
array.obj: array.h dbg.h error.h lg.h lgalt.h libdbg.h malloc.h memall.h \
	 stdio.h string.h types.h

arraytst.obj: array.h dbg.h error.h lg.h lgalt.h libdbg.h malloc.h memall.h \
	 stdio.h stdlib.h types.h

cursors.obj: 2d.h assert.h base.h conio.h cursors.h dbg.h dos.h error.h \
	 fix.h grindex.h i86.h lg.h lgalt.h libdbg.h malloc.h math.h \
	 memall.h mouse.h rect.h region.h stdarg.h stdio.h stdlib.h \
	 string.h types.h

event.obj: array.h assert.h base.h conio.h dbg.h dos.h error.h event.h \
	 i86.h kb.h kbcook.h lg.h lgalt.h libdbg.h malloc.h memall.h \
	 mouse.h projdbg.h rect.h region.h stdio.h stdlib.h string.h \
	 types.h

gadtest.obj: 2d.h array.h assert.h base.h butarray.h conio.h cursors.h \
	 datapath.h dbg.h dos.h error.h event.h fix.h gadgets.h gfx.h \
	 grindex.h i86.h io.h kb.h kbcook.h lg.h lgalt.h libdbg.h malloc.h \
	 math.h memall.h mouse.h mprintf.h projdbg.h pushbutt.h qboxgadg.h \
	 rect.h region.h res.h resource.h restypes.h slider.h stat.h \
	 stdarg.h stdio.h stdlib.h string.h textgadg.h types.h

hottest.obj: dbg.h error.h hash.h hotkey.h kb.h kbcook.h lg.h lgalt.h \
	 libdbg.h malloc.h memall.h stdio.h stdlib.h types.h

oldgdtst.obj: 2d.h array.h assert.h base.h butarray.h conio.h datapath.h \
	 dbg.h dos.h error.h event.h fix.h gadgets.h gfx.h grindex.h i86.h \
	 io.h kb.h kbcook.h lg.h lgalt.h libdbg.h malloc.h math.h memall.h \
	 mouse.h mprintf.h projdbg.h pushbutt.h rect.h region.h res.h \
	 resource.h restypes.h slider.h stat.h stdarg.h stdio.h stdlib.h \
	 string.h textgadg.h types.h

region.obj: array.h assert.h base.h conio.h datapath.h dbg.h dos.h error.h \
	 event.h gadgets.h i86.h lg.h lgalt.h libdbg.h malloc.h memall.h \
	 projdbg.h rect.h region.h res.h resource.h restypes.h stdio.h \
	 stdlib.h string.h types.h
@



1.11
log
@Makes the new improved slabotronic version of gadtest.
@
text
@d6 2
a7 2
PROG_TARGETS =  regtest arraytst gadtest texttest # citadel
LIB_TARGETS =
d36 1
a36 1
        event.obj array.obj
d38 12
@



1.10
log
@Bugtracking, cursors
@
text
@d30 3
a32 3
        array.obj pushbutt.obj butarray.obj slider.obj textgadg.obj \
        qboxgadg.obj bugtrak.obj cursors.obj      
GADTEST_LIBS = lg.lib mprintf.lib 2d.lib res.lib kb.lib mouse.lib
d63 2
a64 5
butarray.obj: 2d.h array.h assert.h base.h butarray.h conio.h datapath.h \
	 dbg.h dos.h error.h event.h fix.h gadgets.h gfx.h grindex.h i86.h \
	 lg.h lgalt.h libdbg.h malloc.h math.h memall.h mouse.h projdbg.h \
	 rect.h region.h res.h resource.h restypes.h stdarg.h stdio.h \
	 stdlib.h string.h types.h
d66 6
a71 4
gadgets.obj: 2d.h array.h assert.h base.h conio.h datapath.h dbg.h dos.h \
	 error.h event.h fix.h gadgets.h gfx.h grindex.h i86.h lg.h lgalt.h \
	 libdbg.h malloc.h math.h memall.h mouse.h projdbg.h rect.h \
	 region.h res.h resource.h restypes.h stdarg.h stdio.h stdlib.h \
d74 16
a89 1
gadtest.obj: 2d.h array.h assert.h base.h butarray.h conio.h datapath.h \
d94 1
a94 1
	 string.h types.h
d96 3
a98 4
pushbutt.obj: 2d.h array.h assert.h base.h conio.h datapath.h dbg.h dos.h \
	 error.h event.h fix.h gadgets.h grindex.h i86.h lg.h lgalt.h \
	 libdbg.h malloc.h math.h memall.h mouse.h projdbg.h pushbutt.h \
	 rect.h region.h res.h resource.h restypes.h stdarg.h stdio.h \
a99 6

slider.obj: 2d.h array.h assert.h base.h conio.h datapath.h dbg.h dos.h \
	 error.h event.h fix.h gadgets.h grindex.h i86.h lg.h lgalt.h \
	 libdbg.h malloc.h math.h memall.h mouse.h projdbg.h pushbutt.h \
	 rect.h region.h res.h resource.h restypes.h slider.h stdarg.h \
	 stdio.h stdlib.h string.h types.h
@



1.9
log
@text tester, qboxgadg.obj & textgadg.obj
@
text
@d31 1
a31 1
        qboxgadg.obj        
@



1.8
log
@Updated dependencies.
@
text
@d6 1
a6 1
PROG_TARGETS =  regtest arraytst gadtest dummy # citadel
d30 2
a31 1
        array.obj pushbutt.obj butarray.obj slider.obj
d34 4
a37 2
DUMMY_OBJS = dummy.obj
DUMMY_LIBS = lg.lib mprintf.lib
@



1.7
log
@more testing stuff
@
text
@@



1.6
log
@masm.h, dependencies -- attempted fix
@
text
@d6 1
a6 1
PROG_TARGETS =  regtest arraytst gadtest # citadel
d30 2
a31 2
        array.obj
GADTEST_LIBS = lg.lib mprintf.lib 2d.lib res.lib mouse.lib kb.lib
d33 3
d54 1
d60 4
a63 6
array.obj: array.h dbg.h error.h lg.h lgalt.h libdbg.h malloc.h memall.h \
	 stdio.h string.h types.h

gadgets.obj: 2d.h assert.h base.h conio.h dbg.h dos.h error.h fix.h \
	 gadgets.h grindex.h i86.h lg.h lgalt.h libdbg.h malloc.h math.h \
	 memall.h mouse.h projdbg.h rect.h region.h stdarg.h stdio.h \
d66 5
a70 4
gadtest.obj: 2d.h assert.h base.h conio.h dbg.h dos.h error.h fix.h \
	 gadgets.h grindex.h i86.h io.h lg.h lgalt.h libdbg.h malloc.h \
	 math.h memall.h mprintf.h projdbg.h rect.h region.h stat.h \
	 stdarg.h stdio.h stdlib.h string.h types.h
d72 5
a76 1
rect.obj: assert.h base.h conio.h dos.h i86.h rect.h stdio.h stdlib.h \
d79 10
a88 2
region.obj: assert.h base.h conio.h dbg.h dos.h error.h gadgets.h i86.h \
	 lg.h lgalt.h libdbg.h malloc.h memall.h projdbg.h rect.h region.h \
@



1.5
log
@gadtest
@
text
@d57 1
a57 1
	 memasm.h stdio.h string.h types.h
d61 1
a61 1
	 memall.h memasm.h projdbg.h rect.h region.h stdarg.h stdio.h \
d64 5
d72 2
a73 2
region.obj: assert.h base.h conio.h dbg.h dos.h error.h i86.h lg.h lgalt.h \
	 libdbg.h malloc.h memall.h memasm.h projdbg.h rect.h region.h \
@



1.4
log
@fixed stupid type
@
text
@d29 3
a31 2
GADTEST_OBJS = gadgets.obj rect.obj gadtest.obj region.obj 
GADTEST_LIBS = lg.lib mprintf.lib 2d.lib res.lib
@



1.3
log
@changed inc pathh
@
text
@d24 1
a24 1
REGTEST_OBJS = lg.lib mprintf.lib
d45 2
a46 2
!include makefile.rcs
!include inc/makefile.rcs
d48 4
@



1.2
log
@depend
@
text
@d46 1
a46 1
!include ../inc/makefile.rcs
@



1.1
log
@Initial revision
@
text
@d51 14
@

