#
# $Source: x:/prj/tech/libsrc/skel/RCS/makefile $
# $Revision: 2.1 $
# $Author: ept $
# $Date: 1995/10/18 12:56:34 $
#
# Makefile for Skel library
#

MAKETOP = $(CWD)
PROJECT = tech

%include $(MRC)\env.rc
%include $(MRC)\init.rc

LIBTARGS = skel

skel_OBJS = \
        skel\
        sklist\
        skdraw\
        render

skel_HDRS = \
        skel.h

%include $(MRC)/make.rc

