head	 1.1;
branch   ;
access   ;
symbols  ;
locks    ; strict;
comment  @ * @;


1.1
date	 2000.01.24.22.07.35;  author rsmith;  state Exp;
branches ;
next	 ;


desc
@Victory condition var definitions for Thief2 - Mission 16 - Endgame
@



1.1
log
@Initial revision
@
text
@#define M16_GOAL_LEARN 0
#define M16_GOAL_MANUFACTURE 1
#define M16_GOAL_CONNECT 2
#define M16_GOAL_ADJUST_NORM 3
#define M16_GOAL_ADJUST_HARD 4
#define M16_GOAL_ADJUST_EXP 5
#define M16_GOAL_BESNEAKY 6
#define M16_GOAL_EXIT 7
@
