head	 1.9;
branch   ;
access   ;
symbols  ;
locks    ; strict;
comment  @# @;


1.9
date	 1996.10.22.13.15.35;  author TOML;  state Exp;
branches ;
next	 1.8;

1.8
date	 1996.10.01.18.45.25;  author TOML;  state Exp;
branches ;
next	 1.7;

1.7
date	 1996.09.19.18.49.31;  author JON;  state Exp;
branches ;
next	 1.6;

1.6
date	 1996.09.18.12.08.17;  author JON;  state Exp;
branches ;
next	 1.5;

1.5
date	 1996.09.18.11.52.15;  author JON;  state Exp;
branches ;
next	 1.4;

1.4
date	 1996.09.18.11.35.36;  author JON;  state Exp;
branches ;
next	 1.3;

1.3
date	 1996.09.06.11.55.47;  author TOML;  state Exp;
branches ;
next	 1.2;

1.2
date	 1996.08.12.16.43.40;  author TOML;  state Exp;
branches ;
next	 1.1;

1.1
date	 1996.08.06.16.10.15;  author TOML;  state Exp;
branches ;
next	 ;


desc
@@


1.9
log
@Backport to DOS
@
text
@#
# $Source: x:/prj/tech/libsrc/actmovie/rcs/makefile $
# $Revision: 1.8 $
# $Author: TOML $
# $Date: 1996/10/01 18:45:25 $
#
# Makefile for actmovie library
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = actmovie

actmovie_DEFINES =

actmovie_OBJS = actmovie

actmovie_win32_OBJS = amguids amalloc imutil mtype getlgvid

actmovie_opt_objs = imutil

actmovie_HDRS =

%include $(MRC)\make.rc

@


1.8
log
@*** empty log message ***
@
text
@d3 3
a5 3
# $Revision: 1.7 $
# $Author: JON $
# $Date: 1996/09/19 18:49:31 $
d22 3
a24 1
actmovie_OBJS = actmovie amguids amalloc imutil mtype getlgvid
@


1.7
log
@Moved headers to compapi.
@
text
@d3 1
a3 1
# $Revision: 1.6 $
d5 1
a5 1
# $Date: 1996/09/18 12:08:17 $
d22 1
a22 1
actmovie_OBJS = actmovie amguids amalloc imutil mtype
d24 3
a26 1
actmovie_HDRS = 
@


1.6
log
@Make the new constants header.
@
text
@d3 1
a3 1
# $Revision: 1.5 $
d5 1
a5 1
# $Date: 1996/09/18 11:52:15 $
d24 1
a24 1
actmovie_HDRS = movieapi.h movconst.h
@


1.5
log
@Make the movieapi header.
@
text
@d3 1
a3 1
# $Revision: 1.4 $
d5 1
a5 1
# $Date: 1996/09/18 11:35:36 $
d24 1
a24 1
actmovie_HDRS = movieapi.h
@


1.4
log
@Make the new image utilities and media type modules.
@
text
@d3 3
a5 3
# $Revision: 1.3 $
# $Author: TOML $
# $Date: 1996/09/06 11:55:47 $
d24 1
a24 1
actmovie_HDRS =
@


1.3
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.2 $
d5 1
a5 1
# $Date: 1996/08/12 16:43:40 $
d20 3
a22 1
actmovie_OBJS = actmovie amguids amalloc
@


1.2
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 1.1 $
d5 1
a5 1
# $Date: 1996/08/06 16:10:15 $
d20 1
a20 1
actmovie_OBJS = actmovie amguids
@


1.1
log
@Initial revision
@
text
@d2 1
a2 1
# $Source: o:/prj/tech/libsrc/actmovie/RCS/makefile $
d5 1
a5 1
# $Date: 1996/08/06 16:02:29 $
d20 1
a20 1
actmovie_OBJS = actmovie
@
