#
# $Source: x:/prj/tech/libsrc/compapis/RCS/makefile $
# $Revision: 1.13 $
# $Author: TOML $
# $Date: 1997/02/24 23:47:54 $
#
# Makefile for compapis ibrary
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = compapis

compapis_OBJS = genguid1

compapis_HDRS = appagg.h appapi.h appguid.h dispapi.h dispguid.h gshelapi.h \
                gshlguid.h indevapi.h indvguid.h wappapi.h wappguid.h \
                pumpenum.h loopguid.h loopapi.h looptype.h movieapi.h \
                moviguid.h recapi.h recguid.h arqapi.h arqguid.h \
                movconst.h thrmnapi.h thrmguid.h cacheapi.h cachguid.h 

%include $(MRC)\make.rc


