/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// Debug header file x:\prj\tech\h/_babl2.__h made from libdbg.dbg by DBGMAKEH

#ifndef ___BABL2_H
#define ___BABL2_H

#define DB_BABL2 9
#define DS_BABL2_Tasks 0x1
#define DSRC_BABL2_Tasks 0x48000001
#define DS_BABL2_Source 0x2
#define DSRC_BABL2_Source 0x48000002
#define DS_BABL2_DebugVal 0x4
#define DSRC_BABL2_DebugVal 0x48000004
#define DS_BABL2_Interp 0x8
#define DSRC_BABL2_Interp 0x48000008
#define DS_BABL2_AppOps 0x10
#define DSRC_BABL2_AppOps 0x48000010
#define DS_BABL2_Compiler 0x20
#define DSRC_BABL2_Compiler 0x48000020
#define DS_BABL2_Linker 0x40
#define DSRC_BABL2_Linker 0x48000040

#endif
