/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/RCS/aiapp.h 1.4 1997/10/04 17:10:07 TOML Exp $

#ifndef __SAMPAPP_H
#define __SAMPAPP_H

EXTERN void LGAPI AISysCreate();

DEFINE_LG_GUID(UUID_AIApp, 0x32);

//
// KEEP THIS FILE RELATIVELY CLEAR OF JUNK!  DO NOT PUT YOUR SYSTEM'S API HERE!
// DO NOT INCLUDE OTHER HEADER FILES FROM THIS FILE!
//

#endif // __SAMPAPP_H

