/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/RCS/airgame.h 1.3 1997/06/12 17:54:38 mahk Exp $

#ifndef AIRGAME_H
#define AIRGAME_H

////////////////////////////////////////////////////////////
// AIR GAME CODE
//
// (Stuff that I have converted from gamespec_foo to air_foo)
//

EXTERN void air_update_frame(int ms);
EXTERN void air_start_gamemode(void);
EXTERN void air_end_gamemode(void);
EXTERN void air_init_game(void);
EXTERN void air_hud(void);


#endif // AIRGAME_H

