/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/RCS/airinit.h 1.1 1997/01/15 16:24:55 mahk Exp $

#ifndef __AIRINIT_H
#define __AIRINIT_H

EXTERN void LGAPI CreateAIR(void);
DEFINE_LG_GUID(UUID_AIR, 0x43);

//
// KEEP THIS FILE RELATIVELY CLEAR OF JUNK!  DO NOT PUT YOUR SYSTEM'S API HERE! 
// DO NOT INCLUDE OTHER HEADER FILES FROM THIS FILE!
//

#endif // __AIRINIT_H

