/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/RCS/apppid.h 1.1 1997/09/18 00:07:18 mahk Exp $

#ifndef __APPPID_H
#define __APPPID_H

////////////////////////////////////////////////////////////
// App Process ID. 
//
// Ideally there would be some INetworkedProcess agg member that knew this.
//

EXTERN int appPID;      // the Process ID for globalIDs, (usually netConnect)


#endif // __APPPID_H
