/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/RCS/biploop.h 1.2 1998/04/24 14:12:52 TOML Exp $
#ifndef __BIPLOOP_H
#define __BIPLOOP_H

DEFINE_LG_GUID(LOOPID_Biped, 0x34);

EXTERN struct sLoopClientDesc  BipedLoopClientDesc;

//
// KEEP THIS FILE RELATIVELY CLEAR OF JUNK!  DO NOT PUT YOUR SYSTEM'S API HERE! 
// DO NOT INCLUDE OTHER HEADER FILES FROM THIS FILE!
//

 
#endif // __BIPLOOP_H


