/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

///////////////////////////////////////////////////////////////////////////////
// $Source: r:/prj/cam/src/RCS/biptype.h $
// $Author: JON $
// $Date: 1997/02/05 17:41:33 $
// $Revision: 1.2 $
//
// Basic biped data types

#ifndef __BIPTYPE_H
#define __BIPTYPE_H

typedef struct Biped Biped;
typedef struct BipedLengths BipedLengths;
typedef struct BipedModel BipedModel;

#endif // __BIPTYPE_H
