/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/RCS/brloop.h 1.2 1998/04/24 14:12:53 TOML Exp $
#ifndef __BRLOOP_H
#define __BRLOOP_H


// Loop client GUID
DEFINE_LG_GUID(LOOPID_BrushList, 0x3a);

// Loop Client Descriptor
EXTERN struct sLoopClientDesc  BrushListLoopClientDesc;

//
// KEEP THIS FILE RELATIVELY CLEAR OF JUNK!  DO NOT PUT YOUR SYSTEM'S API HERE! 
// DO NOT INCLUDE OTHER HEADER FILES FROM THIS FILE!
//

 
#endif // __BRLOOP_H
