/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/RCS/edinhtyp.h 1.1 1997/04/18 01:44:35 mahk Exp $

#ifndef __EDINHTYP_H
#define __EDINHTYP_H

//
// Inheritance editor forward declarations
//

// various enums for flags and field types
typedef ulong eInheritanceEditorFlags;

// actual structures used when describing structures
typedef struct InheritanceEditor InheritanceEditor;
typedef struct InheritanceEditorDesc InheritanceEditorDesc;

#endif // __EDINHTYP_H
