/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/RCS/edlnktyp.h 1.1 1997/04/11 00:59:48 mahk Exp $

#ifndef __EDLNKTYP_H
#define __EDLNKTYP_H

//
// Link editor forward declarations
//

// various enums for flags and field types
typedef ulong eLinkEditorFlags;

// actual structures used when describing structures
typedef struct LinkEditor LinkEditor;
typedef struct LinkEditorDesc LinkEditorDesc;

typedef struct LinkQueue LinkQueue;
typedef struct IDQueue IDQueue;

#endif // __EDLNKTYP_H
