/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/RCS/edmedmot.h 1.1 1997/10/01 12:14:15 MAT Exp $

/* ----- /-/-/-/-/-/-/-/-/ <<< (((((( /\ )))))) >>> \-\-\-\-\-\-\-\-\ ----- *\
   edmedmot.h

   This is the part of the medium motion data which is needed by the
   editor but not by the game.  Well, actually, it's just the typedef.

\* ----- \-\-\-\-\-\-\-\-\ <<< (((((( \/ )))))) >>> /-/-/-/-/-/-/-/-/ ----- */


#ifndef _EDMEDMOT_H_
#define _EDMEDMOT_H_

// The _change fields are for making the water move: dposition/second.
typedef struct sEdMedMoSurface sEdMedMoSurface;

typedef int tEdMedMoSurfaceIter;

#endif // ~_EDMEDMOT_H_
