/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/t2repos/thief2/src/render/h2xprop.h,v 1.2 2000/01/29 13:38:57 adurant Exp $
#pragma once

#ifndef H2XPROP_H
#define H2XPROP_H
#include <property.h>

//------------------------------------------------------------
// H2X LEVEL PROPERTY NAME
//

#define PROP_H2X_NAME "H2X"
#define PROP_H2XMAX_NAME "H2XMax"


//------------------------------------------------------------
// H2X PROPERTY API
//

EXTERN void H2XPropInit(void);

#endif // H2XPROP_H
