/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

///////////////////////////////////////////////////////////////////////////////
// $Source: x:/prj/tech/libsrc/compapis/RCS/lguuid.h $
// $Author: TOML $
// $Date: 1996/05/02 12:30:10 $
// $Revision: 1.1 $
//

#ifndef __LGUUID_H
#define __LGUUID_H

EXTERN const int g_TopLookingGlassUUID;

#endif /* !__LGUUID_H */
