/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/RCS/magiprop.h 1.1 1997/01/21 21:27:13 CNORDEN Exp $

#ifndef MAGIPROP_H
#define MAGIPROP_H
#include <property.h>

//------------------------------------------------------------
// AIR MAGIC PROPERTY NAME
//

#define PROP_MAGIC_NAME "AirMagic"

//------------------------------------------------------------
// AIR MAGIC PROPERTY API
//

EXTERN void MagicPropInit(void);

#endif // MAGIPROP_H
