/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/RCS/mctype_.h 1.2 1998/05/25 16:11:28 kate Exp $

#ifndef __MCTYPE__H
#define __MCTYPE__H

// this contains forward declarations internal to the motion system

typedef struct sMcMotorState sMcMotorState;
typedef class cMotionCoordinator cMotionCoordinator;
typedef class cMotionPlan cMotionPlan;


#endif
