/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

///////////////////////////////////////////////////////////////////////////////
// $Source: r:/prj/cam/src/RCS/menus.h $
// $Author: TOML $
// $Date: 1997/08/05 14:01:41 $
// $Revision: 1.1 $
//

#ifndef __MENUS_H
#define __MENUS_H

EXTERN void SetMainMenu(const char * pszName);
EXTERN void MenuCommand(unsigned);

#endif /* !__MENUS_H */
