/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/RCS/motdbtyp.h 1.1 1998/04/20 17:37:53 kate Exp $

#ifndef __MOTDBTYP_H
#define __MOTDBTYP_H

#ifdef __cplusplus

// forward declarations of motion database classes

typedef class cMotionSchema cMotionSchema;
typedef class cMotionDatabase cMotionDatabase;
typedef class IMotionSet IMotionSet;

#endif // cplusplus

// forward declarations of internal structures
typedef struct sMotStuff sMotStuff;
typedef struct sMotDesc sMotDesc;
typedef struct sTagDesc sTagDesc;
typedef struct sMotSchemaDesc sMotSchemaDesc;

#endif // __MOTDBTYP_H
