/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/RCS/nfizloop.h 1.1 1997/01/09 20:50:42 mahk Exp $
#ifndef __NFIZLOOP_H
#define __NFIZLOOP_H


// Loop client GUID
DEFINE_LG_GUID(LOOPID_NetPhysics, 0x3c);


//
// Loop Client Factory Descriptor
EXTERN struct sLoopFactoryDesc NetPhysicsLoopFactory;

//
// KEEP THIS FILE RELATIVELY CLEAR OF JUNK!  DO NOT PUT YOUR SYSTEM'S API HERE! 
// DO NOT INCLUDE OTHER HEADER FILES FROM THIS FILE!
//

 
#endif // __NFIZLOOP_H
