/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

/*=========================================================

  Created:  12/14/99 2:19:53 PM

  File:  rgInit.h

  Description:  RenderG headers used for configuration and
               creation of objects


=========================================================*/

// $Header: x:/prj/tech/libsrc/rg/RCS/rginit.h 1.1 1970/01/01 00:00:00 Zarko Exp $

#pragma once 

#ifndef _RGINIT_H
#define _RGINIT_H


//_____INCLUDES_AND_DEFINITIONS___________________________


#ifndef _RGCANVAS_H
#include <rgCanvas.h>
#endif

#ifndef _RGCAPS_H
#include <rgCaps.h>
#endif

#ifndef _RGFACTRY_H
#include <rgFactry.h>
#endif




#endif //_RGINIT_H