/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/shock/RCS/shkcurpr.h 1.1 1998/11/23 15:51:50 XEMU Exp $

#ifndef __SHKCURPR_H
#define __SHKCURPR_H

#define PROP_WORLDCURSOR_NAME "WorldCursor"
EXTERN IStringProperty *gPropWorldCursor;

#define PROP_INVCURSOR_NAME "InvCursor"
EXTERN IStringProperty *gPropInvCursor;

#define PROP_USECURSOR_NAME "UseCursor"
EXTERN IStringProperty *gPropUseCursor;

#define PROP_USETYPE_NAME "UseType"
EXTERN IIntProperty *gPropUseType;

#endif