/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/shock/RCS/shkincst.h 1.2 1999/01/02 13:53:18 XEMU Exp $

#ifndef __SHKINCST_H
#define __SHKINCST_H

// Header file for incest constants

#define MAX_INV_COLUMNS  15
#define MAX_INV_ROWS     3
#define MAX_INV_ITEMS   (MAX_INV_COLUMNS * MAX_INV_ROWS)

#define INV_ICON_WIDTH  35
#define INV_ICON_HEIGHT 34

#define SHOCKCONTAIN_PDOLLBASE   1000

#endif