/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/RCS/shkinit.h 1.1 1997/11/26 13:03:48 XEMU Exp $

#ifndef __SHKINIT_H
#define __SHKINIT_H

EXTERN void LGAPI CreateShock(void);
DEFINE_LG_GUID(UUID_SHOCK, 0xc1);

//
// KEEP THIS FILE RELATIVELY CLEAR OF JUNK!  DO NOT PUT YOUR SYSTEM'S API HERE! 
// DO NOT INCLUDE OTHER HEADER FILES FROM THIS FILE!
//

#endif // __AIRINIT_H

