/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/shock/RCS/shkmfddm.h 1.2 1998/12/16 20:50:24 XEMU Exp $

#ifndef __SHKMFDDM_H
#define __SHKMFDDM_H

/*
#define RMFD_X 450
#define RMFD_Y 2
#define RMFD_W 188
#define RMFD_H 300

#define LMFD_X 2
#define LMFD_Y 2
#define LMFD_W 188
#define LMFD_H 300
*/  

#define RMFD_X 450
#define RMFD_Y 124
#define RMFD_W 188
#define RMFD_H 300

#define LMFD_X 2
#define LMFD_Y 124
#define LMFD_W 188
#define LMFD_H 300

#endif