/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/shock/RCS/shknetap.h 1.1 1999/10/20 16:45:06 Justin Exp $
//
// Shock networking services
//
// This module mainly exists to help out the networking code, rather than
// for Shock per se.
//

#ifndef __SHKNETAP_H
#define __SHKNETAP_H

EXTERN void ShockNetServicesCreate();

#endif // !__SHKNETAP_H
