/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

////////////////////////////////////////////
// $Header: r:/prj/cam/src/shock/RCS/shkpsity.h 1.2 1998/08/30 18:44:23 JON Exp $
//
// Psionics system - basic types
//

#ifndef __SHKPSITY_H
#define __SHKPSITY_H

// Player current psi state
struct sPsiState;

// Data for each psi power
struct sPsiPower;

// Player's current power state
typedef int ePsiPowerState;

// Psi power type (shot, shield, etc.)
typedef int ePsiPowerType;

#endif