/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/shock/RCS/shksound.h 1.1 1999/01/09 15:55:29 JON Exp $

#pragma once
#ifndef __SHKSOUND_H
#define __SHKSOUND_H


////////////////////////////////////////////////////////////
// SHOCK-SPECFIC SOUND STUFF
//

EXTERN void ShockSoundInit(void); 
EXTERN void ShockSoundTerm(void); 

#endif // __SHKSOUND_H
