/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/shock/RCS/shksvbnd.h 1.2 1999/06/06 03:00:51 mahk Exp $

#ifndef __SHKSVBND_H
#define __SHKSVBND_H

EXTERN void SwitchToShockLoadBndMode(BOOL push);
EXTERN void SwitchToShockSaveBndMode(BOOL push); 

EXTERN void ShockInitBindSaveLoad(void); 
EXTERN void ShockTermBindSaveLoad(void); 


#endif // __SHKSVBND_H
