/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/shock/RCS/shkwsprp.h 1.1 1998/09/15 21:58:52 XEMU Exp $

#ifndef _SHKWSPRP_H
#define _SHKWSPRP_H

// Setting text properties
#define PROP_SETTINGTEXT1_NAME "Sett1"
#define PROP_SETTINGTEXT2_NAME "Sett2"
#define PROP_SETTINGHEAD1_NAME "SHead1"
#define PROP_SETTINGHEAD2_NAME "SHead2"
EXTERN IStringProperty* gPropSettingText1;
EXTERN IStringProperty* gPropSettingText2;
EXTERN IStringProperty* gPropSettingHead1;
EXTERN IStringProperty* gPropSettingHead2;

#endif