/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

// $Header: r:/prj/cam/src/shock/RCS/transmod.h 1.3 1999/04/30 18:28:25 mahk Exp $

#ifndef __TRANSMOD_H
#define __TRANSMOD_H

// These functions are actually implemented in shklding.cpp 
EXTERN void TransModeSwitchLevel(const char *level, int marker, uint flags);
EXTERN void TransModeLoadGame(int slot);



#endif
