/*
@Copyright Looking Glass Studios, Inc.
1996,1997,1998,1999,2000 Unpublished Work.
*/

/*	This file created by RESTOOL */

#ifndef __VOYBIPED_H
#define __VOYBIPED_H

#define RES_bip_costumes 0x2b0b		// (11019)
#define RES_vcosMalHBMParts 0x2b0c		// (11020)
#define REF_vmaleH00 0x2b0c0000		
#define REF_vmaleH01 0x2b0c0001		
#define REF_vmaleH02 0x2b0c0002		
#define REF_vmaleH03 0x2b0c0003		
#define REF_vmaleH04 0x2b0c0004		
#define REF_vmaleH05 0x2b0c0005		
#define REF_vmaleH06 0x2b0c0006		
#define RES_vcosFemHBMParts 0x2b0d		// (11021)
#define REF_vfemaH00 0x2b0d0000		
#define REF_vfemaH01 0x2b0d0001		
#define REF_vfemaH02 0x2b0d0002		
#define REF_vfemaH03 0x2b0d0003		
#define REF_vfemaH04 0x2b0d0004		
#define REF_vfemaH05 0x2b0d0005		
#define REF_vfemaH06 0x2b0d0006		
#define RES_cosFemaleTestBMParts 0x2b0e		// (11022)
#define REF_ftest00 0x2b0e0000		
#define REF_ftest01 0x2b0e0001		
#define REF_ftest02 0x2b0e0002		
#define REF_ftest03 0x2b0e0003		
#define REF_ftest04 0x2b0e0004		
#define REF_ftest05 0x2b0e0005		
#define REF_ftest06 0x2b0e0006		
#define RES_cosMaleTestBMParts 0x2b0f		// (11023)
#define REF_mtest00 0x2b0f0000		
#define REF_mtest01 0x2b0f0001		
#define REF_mtest02 0x2b0f0002		
#define REF_mtest03 0x2b0f0003		
#define REF_mtest04 0x2b0f0004		
#define REF_mtest05 0x2b0f0005		
#define REF_mtest06 0x2b0f0006		
#define RES_vcosMalRedBMPal 0x2b3e		// (11070)
#define RES_vcosMalYelBMPal 0x2b3f		// (11071)
#define RES_vcosMalBluBMPal 0x2b40		// (11072)
#define RES_vcosFemRedBMPal 0x2b41		// (11073)
#define RES_femTestBMPal 0x2b42		// (11074)
#define RES_maleTestBMPal 0x2b43		// (11075)
#define RES_vcosMalRedBMPalT 0x2b57		// (11095)
#define RES_vcosMalYelBMPalT 0x2b58		// (11096)
#define RES_vcosMalBluBMPalT 0x2b59		// (11097)
#define RES_vcosFemRedBMPalT 0x2b5a		// (11098)
#define RES_femTestBMPalT 0x2b5b		// (11099)
#define RES_maleTestBMPalT 0x2b5c		// (11100)
#define RES_domiHeadPal 0x2ba2		// (11170)
#define RES_tuvokHeadPal 0x2ba3		// (11171)
#define RES_kimHeadPal 0x2ba4		// (11172)
#define RES_parisHeadPal 0x2ba5		// (11173)
#define RES_doctorHeadPal 0x2ba6		// (11174)
#define RES_kesHeadPal 0x2ba7		// (11175)
#define RES_neelixHeadPal 0x2ba8		// (11176)
#define RES_torresHeadPal 0x2ba9		// (11177)
#define RES_chakoteyHeadPal 0x2baa		// (11178)
#define RES_janeHeadPal 0x2bab		// (11179)
#define RES_domiHeadPalT 0x2bbb		// (11195)
#define RES_tuvokHeadPalT 0x2bbc		// (11196)
#define RES_kimHeadPalT 0x2bbd		// (11197)
#define RES_parisHeadPalT 0x2bbe		// (11198)
#define RES_doctorHeadPalT 0x2bbf		// (11199)
#define RES_kesHeadPalT 0x2bc0		// (11200)
#define RES_neelixHeadPalT 0x2bc1		// (11201)
#define RES_torresHeadPalT 0x2bc2		// (11202)
#define RES_chakoteyHeadPalT 0x2bc3		// (11203)
#define RES_janeHeadPalT 0x2bc4		// (11204)
#define RES_vhandHBMParts 0x2bd4		// (11220)
#define REF_vhandH00 0x2bd40000		
#define REF_dum2 0x2bd40001		
#define RES_domiHiBMParts 0x2b70		// (11120)
#define REF_domiH00 0x2b700000		
#define REF_dum5 0x2b700001		
#define RES_tuvokHeadHiBMParts 0x2b71		// (11121)
#define REF_tuvH00 0x2b710000		
#define REF_dum4 0x2b710001		
#define RES_kimHeadHiBMParts 0x2b72		// (11122)
#define REF_kimH00 0x2b720000		
#define REF_dum6 0x2b720001		
#define RES_parisHeadHiBMParts 0x2b73		// (11123)
#define REF_parH00 0x2b730000		
#define REF_dum7 0x2b730001		
#define RES_doctorHeadHiBMParts 0x2b74		// (11124)
#define REF_docH00 0x2b740000		
#define REF_dum8 0x2b740001		
#define RES_kesHeadHiBMParts 0x2b75		// (11125)
#define REF_kesH00 0x2b750000		
#define REF_dum9 0x2b750001		
#define RES_neelixHeadHiBMParts 0x2b76		// (11126)
#define REF_nelH00 0x2b760000		
#define REF_dum10 0x2b760001		
#define RES_torresHeadHiBMParts 0x2b77		// (11127)
#define REF_torH00 0x2b770000		
#define REF_dum11 0x2b770001		
#define RES_chakotayHeadHiBMParts 0x2b78		// (11128)
#define REF_chakH00 0x2b780000		
#define REF_dum12 0x2b780001		
#define RES_janeHeadHiBMParts 0x2b79		// (11129)
#define REF_janeH00 0x2b790000		
#define REF_dum13 0x2b790001		
#define RES_domiFaceDecalBMParts 0x2c88		// (11400)
#define REF_domiTk00 0x2c880000		
#define REF_domiTk01 0x2c880001		
#define REF_domiTk02 0x2c880002		
#define RES_tuvFaceDecalBMParts 0x2c89		// (11401)
#define REF_tuvTk00 0x2c890000		
#define REF_tuvTk01 0x2c890001		
#define REF_tuvTk02 0x2c890002		
#define RES_kimFaceDecalBMParts 0x2c8a		// (11402)
#define REF_kimTk00 0x2c8a0000		
#define REF_kimTk01 0x2c8a0001		
#define REF_kimTk02 0x2c8a0002		
#define RES_parFaceDecalBMParts 0x2c8b		// (11403)
#define REF_parTk00 0x2c8b0000		
#define REF_parTk01 0x2c8b0001		
#define REF_parTk02 0x2c8b0002		
#define RES_docFaceDecalBMParts 0x2c8c		// (11404)
#define REF_docTk00 0x2c8c0000		
#define REF_docTk01 0x2c8c0001		
#define REF_docTk02 0x2c8c0002		
#define RES_kesFaceDecalBMParts 0x2c8d		// (11405)
#define REF_kesTk00 0x2c8d0000		
#define REF_kesTk01 0x2c8d0001		
#define REF_kesTk02 0x2c8d0002		
#define RES_nelFaceDecalBMParts 0x2c8e		// (11406)
#define REF_nelTk00 0x2c8e0000		
#define REF_nelTk01 0x2c8e0001		
#define REF_nelTk02 0x2c8e0002		
#define RES_torFaceDecalBMParts 0x2c8f		// (11407)
#define REF_torTk00 0x2c8f0000		
#define REF_torTk01 0x2c8f0001		
#define REF_torTk02 0x2c8f0002		
#define RES_chakFaceDecalBMParts 0x2c90		// (11408)
#define REF_chakTk00 0x2c900000		
#define REF_chakTk01 0x2c900001		
#define REF_chakTk02 0x2c900002		
#define RES_janeFaceDecalBMParts 0x2c91		// (11409)
#define REF_janeTk00 0x2c910000		
#define REF_janeTk01 0x2c910001		
#define REF_janeTk02 0x2c910002		
#define RES_skm_BIP_SYM 0x2af8		// (11000)
#define RES_skm_BIP_ASYM 0x2af9		// (11001)
#define RES_BODY326 0x12c		// (300)
#define RES_HEAD284 0x12d		// (301)
#define RES_BODY208 0x12e		// (302)
#define RES_HEAD284T 0x12f		// (303)
#define RES_HEAD431 0x130		// (304)
#define RES_CUBE 0x131		// (305)
#define RES_VOYMAN 0x132		// (306)
#define RES_VOYCOS1 0x190		// (400)
#define RES_HEADWRAP 0x191		// (401)
#define RES_BIPEDPAL 0x192		// (402)
#define RES_DEPTHPAL 0x193		// (403)

#endif
