#
# $Header: x:/prj/tech/libsrc/gadget/RCS/makefile 1.9 1998/07/02 13:21:21 PATMAC Exp $

MAKETOP = $(CWD)

PROJECT ?= TECH
PRJBACK ?= x:\prj

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS=gadget

gadget_OBJS=gadget drawelem util2d gcompose uibutton gadblist gadtext \
        uitexted guistyle

gadget_HDRS=gadget.h drawelem.h util2d.h lgadover.h utilcomp.h \
        gcompose.h uibutton.h gadblist.h gadtext.h uitexted.h \
        guistyle.h gadbase.h gadbutt.h gadbox.h gadscale.h gadmenu.h gadint.h


%include  $(MRC)\make.rc

