// $Header: x:/prj/tech/libsrc/mp/RCS/makefile 1.3 1996/11/21 13:11:59 kate Exp $

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = mp

mp_DEFINES =

mp_OBJS = qt mpinit mplist mpmot mpstack mpupdate mploco mpvm

mp_HDRS = mp.h multiped.h qt.h motion.h motstruc.h mputil.h mpstack.h mplist.h

%include $(MRC)\make.rc





