# $Source: x:/prj/tech/libsrc/vec2/RCS/makefile $
# $Revision: 1.2 $
# $Author: JON $
# $Date: 1996/10/10 17:48:36 $

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = vec2

vec2_OBJS = vec2

vec2_HDRS = vec2.h

%include $(MRC)\make.rc
