#
# $Source: x:/prj/tech/libsrc/comtools/RCS/makefile $
# $Revision: 1.14 $
# $Author: TOML $
# $Date: 1998/02/19 10:34:43 $
#
# Makefile for comtools library
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = comtools

COMTOOLS_OBJS = comtools genagg geniset interset pintarr pguidset comconn

COMTOOLS_HDRS = comtools.h objcoll.h objcguid.h interset.h genagg.h \
                geniset.h pguidset.h pintarr.h constrid.h aggmemb.h \
                comconn.h

%include $(MRC)\make.rc
