// $Header: x:/prj/tech/libsrc/mm/RCS/makefile 1.1 1997/08/22 19:39:12 kate Exp $

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = mm

mm_OBJS = render sortpoly xformseg debug
#utils light

mm_HDRS= mms.h mm.h mmd.h

%include $(MRC)\make.rc


