head	 1.9;
branch   ;
access   ;
symbols  ;
locks    ; strict;
comment  @# @;


1.9
date	 1998.07.02.13.21.21;  author PATMAC;  state Exp;
branches ;
next	 1.8;

1.8
date	 1996.12.11.00.32.35;  author mahk;  state Exp;
branches ;
next	 1.7;

1.7
date	 1996.08.26.02.08.21;  author mahk;  state Exp;
branches ;
next	 1.6;

1.6
date	 1996.08.19.16.19.32;  author mahk;  state Exp;
branches ;
next	 1.5;

1.5
date	 1996.07.30.19.28.41;  author mahk;  state Exp;
branches ;
next	 1.4;

1.4
date	 1996.07.25.03.44.34;  author mahk;  state Exp;
branches ;
next	 1.3;

1.3
date	 1996.07.20.21.44.35;  author mahk;  state Exp;
branches ;
next	 1.2;

1.2
date	 1996.07.20.21.42.44;  author mahk;  state Exp;
branches ;
next	 1.1;

1.1
date	 1996.05.21.13.37.36;  author xemu;  state Exp;
branches ;
next	 ;


desc
@makefile for the gadget\UI system
@


1.9
log
@Added gadint.h to headers
@
text
@#
# $Header: x:/prj/tech/libsrc/gadget/rcs/makefile 1.8 1996/12/11 00:32:35 mahk Exp $

MAKETOP = $(CWD)

PROJECT ?= TECH
PRJBACK ?= x:\prj

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS=gadget

gadget_OBJS=gadget drawelem util2d gcompose uibutton gadblist gadtext \
        uitexted guistyle

gadget_HDRS=gadget.h drawelem.h util2d.h lgadover.h utilcomp.h \
        gcompose.h uibutton.h gadblist.h gadtext.h uitexted.h \
        guistyle.h gadbase.h gadbutt.h gadbox.h gadscale.h gadmenu.h gadint.h


%include  $(MRC)\make.rc

@


1.8
log
@setvmode 22 for austin.
@
text
@d2 1
a2 1
# $Header: x:/prj/tech/libsrc/gadget/rcs/makefile 1.7 1996/08/26 02:08:21 mahk Exp $
d20 1
a20 1
        guistyle.h gadbase.h gadbutt.h gadbox.h gadscale.h gadmenu.h
@


1.7
log
@added a bunch of new headers.
@
text
@d2 1
a2 1
# $Header: x:/prj/tech/libsrc/gadget/rcs/makefile 1.6 1996/08/19 16:19:32 mahk Exp $
d6 2
a7 2
PROJECT = TECH
PRJBACK = x:\prj
@


1.6
log
@checking in to correct tree.
@
text
@d2 1
a2 1
# $Header: r:/prj/cam/libsrc/gadget/rcs/makefile 1.6 1996/08/19 15:31:52 mahk Exp $
d20 1
a20 1
        guistyle.h
@


1.5
log
@Added styles and textboxes
@
text
@d2 1
a2 1
# $Header: r:/prj/cam/libsrc/gadget/rcs/makefile 1.4 1996/07/25 03:44:34 mahk Exp $
d6 2
a7 2
PROJECT = CAM
PRJBACK = R:\prj
@


1.4
log
@bunches of new modules.
@
text
@d2 1
a2 1
# $Header: r:/prj/cam/libsrc/gadget/rcs/makefile 1.3 1996/07/20 21:44:35 mahk Exp $
d15 2
a16 1
gadget_OBJS=gadget drawelem util2d gcompose uibutton gadblist 
d19 2
a20 1
        gcompose.h uibutton.h gadblist.h
@


1.3
log
@changed coreback to prjback.
@
text
@d2 1
a2 1
# $Header: r:/prj/cam/libsrc/gadget/rcs/makefile 1.2 1996/07/20 21:42:44 mahk Exp $
d15 1
a15 1
gadget_OBJS=gadget drawelem util2d
d17 3
a19 1
gadget_HDRS=gadget.h drawelem.h util2d.h lgadover.h utilcomp.h
@


1.2
log
@setup for local cam gadget library.
@
text
@d2 1
a2 1
# $Header: r:/prj/cam/libsrc/gadget/rcs/makefile 1.1 1996/05/21 13:37:36 xemu Exp $
d7 1
a7 1
COREBACK = R:\prj
@


1.1
log
@Initial revision
@
text
@d2 1
a2 1
# $Header:  $
d6 2
a7 1
PROJECT = tech
@
