#
# $Source: x:/prj/tech/libsrc/mprintf/RCS/makefile $
# $Revision: 2.4 $
# $Author: TOML $
# $Date: 1996/04/08 16:53:55 $
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = mprintf

mprintf_OBJS = mprintf
mprintf_HDRS = mprintf.h

%include $(MRC)\make.rc

