head	 2.22;
branch   ;
access   ;
symbols  SHIPPED_F95:2.1 oldnmk:1.25.1 FLT_SHIP:1.25.1.1;
locks    ; strict;
comment  @# @;


2.22
date	 1998.05.01.14.01.08;  author JUSTIN;  state Exp;
branches ;
next	 2.21;

2.21
date	 1997.09.06.15.00.55;  author TOML;  state Exp;
branches ;
next	 2.20;

2.20
date	 1997.07.21.14.13.08;  author TOML;  state Exp;
branches ;
next	 2.19;

2.19
date	 1997.07.15.21.29.22;  author TOML;  state Exp;
branches ;
next	 2.18;

2.18
date	 1997.03.10.13.35.03;  author TOML;  state Exp;
branches ;
next	 2.17;

2.17
date	 1997.02.15.17.44.14;  author TOML;  state Exp;
branches ;
next	 2.16;

2.16
date	 1997.01.30.13.50.16;  author TOML;  state Exp;
branches ;
next	 2.15;

2.15
date	 1997.01.29.17.53.12;  author TOML;  state Exp;
branches ;
next	 2.14;

2.14
date	 1997.01.20.15.24.11;  author TOML;  state Exp;
branches ;
next	 2.13;

2.13
date	 1996.12.10.13.54.56;  author JAEMZ;  state Exp;
branches ;
next	 2.12;

2.12
date	 1996.11.02.15.27.01;  author TOML;  state Exp;
branches ;
next	 2.11;

2.11
date	 1996.09.20.15.02.04;  author TOML;  state Exp;
branches ;
next	 2.10;

2.10
date	 1996.08.28.13.57.21;  author TOML;  state Exp;
branches ;
next	 2.9;

2.9
date	 1996.07.23.09.53.27;  author TOML;  state Exp;
branches ;
next	 2.8;

2.8
date	 1996.07.15.17.49.06;  author TOML;  state Exp;
branches ;
next	 2.7;

2.7
date	 1996.06.19.16.04.38;  author TOML;  state Exp;
branches ;
next	 2.6;

2.6
date	 1996.05.29.16.55.45;  author TOML;  state Exp;
branches ;
next	 2.5;

2.5
date	 1996.05.29.16.51.55;  author TOML;  state Exp;
branches ;
next	 2.4;

2.4
date	 1996.05.29.11.50.50;  author TOML;  state Exp;
branches ;
next	 2.3;

2.3
date	 1996.04.30.18.23.10;  author TOML;  state Exp;
branches ;
next	 2.2;

2.2
date	 1996.04.08.16.53.40;  author TOML;  state Exp;
branches ;
next	 2.1;

2.1
date	 1995.10.02.20.07.18;  author ept;  state Exp;
branches ;
next	 1.25;

1.25
date	 1994.11.13.13.22.40;  author ept;  state Exp;
branches 1.25.1.1;
next	 1.24;

1.24
date	 1994.08.12.17.08.18;  author jak;  state Exp;
branches ;
next	 1.23;

1.23
date	 1994.08.04.22.27.03;  author kaboom;  state Exp;
branches ;
next	 1.22;

1.22
date	 1994.07.29.01.22.43;  author dc;  state Exp;
branches ;
next	 1.21;

1.21
date	 1994.07.08.17.39.28;  author rex;  state Exp;
branches ;
next	 1.20;

1.20
date	 1994.06.01.17.14.11;  author junochoe;  state Exp;
branches ;
next	 1.19;

1.19
date	 1994.02.28.10.53.02;  author rex;  state Exp;
branches ;
next	 1.18;

1.18
date	 1993.11.03.19.06.12;  author tjs;  state Exp;
branches ;
next	 1.17;

1.17
date	 1993.11.03.18.30.29;  author tjs;  state Exp;
branches ;
next	 1.16;

1.16
date	 1993.09.30.18.37.28;  author rex;  state Exp;
branches ;
next	 1.15;

1.15
date	 1993.09.13.11.11.17;  author dfan;  state Exp;
branches ;
next	 1.14;

1.14
date	 1993.08.11.17.31.47;  author rex;  state Exp;
branches ;
next	 1.13;

1.13
date	 1993.08.06.11.00.03;  author rex;  state Exp;
branches ;
next	 1.12;

1.12
date	 1993.07.09.09.35.12;  author rex;  state Exp;
branches ;
next	 1.11;

1.11
date	 1993.05.01.20.33.02;  author xemu;  state Exp;
branches ;
next	 1.10;

1.10
date	 1993.04.22.11.39.53;  author rex;  state Exp;
branches ;
next	 1.9;

1.9
date	 1993.04.08.10.28.16;  author rex;  state Exp;
branches ;
next	 1.8;

1.8
date	 1993.03.24.12.12.37;  author matt;  state Exp;
branches ;
next	 1.7;

1.7
date	 1993.03.24.12.02.27;  author matt;  state Exp;
branches ;
next	 1.6;

1.6
date	 1993.03.22.19.10.22;  author matt;  state Exp;
branches ;
next	 1.5;

1.5
date	 1993.03.22.18.04.18;  author rex;  state Exp;
branches ;
next	 1.4;

1.4
date	 1993.03.04.18.45.27;  author rex;  state Exp;
branches ;
next	 1.3;

1.3
date	 1993.03.04.11.51.27;  author rex;  state Exp;
branches ;
next	 1.2;

1.2
date	 1993.01.29.17.31.52;  author rex;  state Exp;
branches ;
next	 1.1;

1.1
date	 1993.01.29.09.48.03;  author rex;  state Exp;
branches ;
next	 ;

1.25.1.1
date	 1994.12.10.10.24.29;  author lmfeeney;  state Exp;
branches ;
next	 ;


desc
@@


2.22
log
@Added dptest executable, which tests Datapath and DatapathDir.
@
text
@#
# $Source: x:/prj/tech/libsrc/lg/rcs/makefile $
# $Revision: 2.21 $
# $Author: TOML $
# $Date: 1997/09/06 15:00:55 $
#

MAKETOP = $(CWD)
PROJECT = tech

%include $(MRC)\env.rc
%include $(MRC)\init.rc

LIBTARGS = lg

EXETYPE = con
SPEC_EXETARGS = dptest
DEV_DPTEST = dptest

lg_OBJS = bugtrak datapath dbg dbgcfg dbgpp exit lgprntf lgsprntf \
    memgrow memstat oheapwal stack tmpalloc lglog lgassert \
    stktrace  breakkey hashfns thrdtool appagg codewrit \
    dpathdir memreq crc32 findfile coremutx timings

lg_HDRS = bugtrak.h datapath.h dbg.h dbgmacro.inc dbgpp.h lg.h \
	lgalt.h lgprntf.h lgsprntf.h memmacro.inc memstat.h \
	tmpalloc.h lg.inc dbg.inc lglog.h lglocmsg.h lgassert.h \
	stktrace.h breakkey.h hashfns.h thrdtool.h \
	codewrit.h memreq.h crc32.h findfile.h coremutx.h timings.h

dptest_objs = dptest
dptest_libs = lg mprintf cpptools comtools compapis appcore templgen \
               lgalloc lgstream

# can't do
# h2i_files = lg.inc memall.inc dbg.inc

%include $(MRC)/make.rc

@


2.21
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 2.20 $
d5 1
a5 1
# $Date: 1997/07/21 14:13:08 $
d16 4
d30 4
@


2.20
log
@*** empty log message ***
@
text
@d2 2
a3 2
# $Source: x:/prj/tech/libsrc/lg/RCS/makefile $
# $Revision: 2.19 $
d5 1
a5 1
# $Date: 1997/07/15 21:29:22 $
d19 1
a19 1
    dpathdir memreq crc32 findfile coremutx
@


2.19
log
@*** empty log message ***
@
text
@d2 2
a3 2
# $Source: x:/prj/tech/libsrc/lg/rcs/makefile $
# $Revision: 2.18 $
d5 1
a5 1
# $Date: 1997/03/10 13:35:03 $
d25 1
a25 1
	codewrit.h memreq.h crc32.h findfile.h coremutx.h
@


2.18
log
@threading
@
text
@d3 1
a3 1
# $Revision: 2.17 $
d5 1
a5 1
# $Date: 1997/02/15 17:44:14 $
d17 2
a18 2
    memall memgrow memstat oheapwal stack tmpalloc lglog lgassert \
    stktrace pool poolimp breakkey hashfns thrdtool appagg codewrit \
d22 4
a25 4
	lgalt.h lgprntf.h lgsprntf.h memall.h memmacro.inc memstat.h \
	tmpalloc.h lg.inc memall.inc dbg.inc lglog.h lglocmsg.h lgassert.h \
	stktrace.h pool.h poolimp.h breakkey.h hashfns.h thrdtool.h \
	codewrit.h memreq.h crc32.h findfile.h virtmem.h coremutx.h
@


2.17
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 2.16 $
d5 1
a5 1
# $Date: 1997/01/30 13:50:16 $
d19 1
a19 1
    dpathdir memreq crc32 findfile
d25 1
a25 1
	codewrit.h memreq.h crc32.h findfile.h virtmem.h
@


2.16
log
@findfile
@
text
@d3 1
a3 1
# $Revision: 2.15 $
d5 1
a5 1
# $Date: 1997/01/29 17:53:12 $
d25 1
a25 1
	codewrit.h memreq.h crc32.h findfile.h
@


2.15
log
@crc
@
text
@d3 1
a3 1
# $Revision: 2.14 $
d5 1
a5 1
# $Date: 1997/01/20 15:24:11 $
d19 1
a19 1
    dpathdir memreq crc32
d25 1
a25 1
	codewrit.h memreq.h crc32.h
@


2.14
log
@*** empty log message ***
@
text
@d3 3
a5 3
# $Revision: 2.13 $
# $Author: JAEMZ $
# $Date: 1996/12/10 13:54:56 $
d19 1
a19 1
    dpathdir memreq
d25 1
a25 1
	codewrit.h memreq.h
@


2.13
log
@Added dpathdir
@
text
@d3 3
a5 3
# $Revision: 2.12 $
# $Author: TOML $
# $Date: 1996/11/02 15:27:01 $
d17 3
a19 3
	memall memgrow memstat oheapwal stack tmpalloc lglog lgassert \
	stktrace pool poolimp breakkey hashfns thrdtool appagg codewrit \
        dpathdir
d25 1
a25 1
	codewrit.h
@


2.12
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 2.11 $
d5 1
a5 1
# $Date: 1996/09/20 15:02:04 $
d18 2
a19 1
	stktrace pool poolimp breakkey hashfns thrdtool appagg codewrit
@


2.11
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 2.10 $
d5 1
a5 1
# $Date: 1996/08/28 13:57:21 $
d18 1
a18 1
	stktrace pool poolimp breakkey hashfns thrdtool appagg
d23 2
a24 1
	stktrace.h pool.h poolimp.h breakkey.h hashfns.h thrdtool.h
@


2.10
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 2.9 $
d5 1
a5 1
# $Date: 1996/07/23 09:53:27 $
d18 1
a18 1
	stktrace pool poolimp breakkey hashfns thrdtool
@


2.9
log
@*** empty log message ***
@
text
@d2 2
a3 2
# $Source: x:/prj/tech/libsrc/lg/RCS/makefile $
# $Revision: 2.8 $
d5 1
a5 1
# $Date: 1996/07/15 17:49:06 $
d18 1
a18 1
	stktrace pool poolimp breakkey hashfns
d23 1
a23 1
	stktrace.h pool.h poolimp.h breakkey.h hashfns.h
@


2.8
log
@*** empty log message ***
@
text
@d2 2
a3 2
# $Source: x:/prj/tech/libsrc/lg/rcs/makefile $
# $Revision: 2.7 $
d5 1
a5 1
# $Date: 1996/06/19 16:04:38 $
d23 1
a23 1
	stktrace.h pool.h breakkey.h hashfns.h
@


2.7
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 2.6 $
d5 1
a5 1
# $Date: 1996/05/29 16:55:45 $
d18 1
a18 1
	stktrace pool poolimp breakkey
d23 1
a23 1
	stktrace.h pool.h breakkey.h
@


2.6
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 2.5 $
d5 1
a5 1
# $Date: 1996/05/29 16:51:55 $
d18 1
a18 1
	stktrace pool poolimp
d23 1
a23 1
	stktrace.h pool.h
@


2.5
log
@Added pools
@
text
@d3 1
a3 1
# $Revision: 2.4 $
d5 1
a5 1
# $Date: 1996/05/29 11:50:50 $
d23 1
a23 1
	stktrace.h poolimp.h
@


2.4
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 2.3 $
d5 1
a5 1
# $Date: 1996/04/30 18:23:10 $
d18 1
a18 1
	stktrace
d23 1
a23 1
	stktrace.h
@


2.3
log
@*** empty log message ***
@
text
@d3 1
a3 1
# $Revision: 2.2 $
d5 1
a5 1
# $Date: 1996/04/08 16:53:40 $
d17 2
a18 1
	memall memgrow memstat oheapwal stack tmpalloc lglog lgassert
d22 2
a23 1
	tmpalloc.h lg.inc memall.inc dbg.inc lglog.h lglocmsg.h lgassert.h
@


2.2
log
@*** empty log message ***
@
text
@d2 4
a5 4
# $Source: x:/prj/tech/libsrc/lg/RCS/makefile $
# $Revision: 2.1 $
# $Author: ept $
# $Date: 1995/10/02 20:07:18 $
d17 1
a17 1
	memall memgrow memstat oheapwal stack tmpalloc
d21 1
a21 1
	tmpalloc.h lg.inc memall.inc dbg.inc
@


2.1
log
@New branch to get rid of the nmk branch.
@
text
@d2 4
a5 4
# $Source: r:/prj/lib/src/lg/rcs/makefile $
# $Revision: 1.25.1.1 $
# $Author: lmfeeney $
# $Date: 1994/12/10 10:24:29 $
d9 1
a9 1
PROJECT = windex
@


1.25
log
@Added mfreetst to proj targets.
@
text
@d3 3
a5 3
# $Revision: 1.24 $
# $Author: jak $
# $Date: 1994/08/12 17:08:18 $
a6 2
# makefile for lg library.
#
d8 2
a9 4
DEBUG_ON = 1
SPEW_ON = 1
WARN_ON = 1
DBG_ON = 1
d11 2
a12 13
COMPILER = watcom
SRCDIR = r:\prj\lib\src\lg
RELDIR = r:\prj\lib\rel
OBJDIR = obj
LIBDIR = $(RELDIR)
INCDIR = $(RELDIR)
BINDIR = n:\bin
INCPATH = . $(SRCDIR) $(RELDIR)
LIBPATH = $(RELDIR)
PROG_TARGETS = dbgmakeh dbgtest stacktst mfreetst
LIB_TARGETS = lg
INST_TARGETS = lg dbgmakeh
EXTRA_TARGETS =
d14 1
a14 9
LG_SRCS = bugtrak.c dbg.c dbgcfg.c dbgpp.cc datapath.c exit.c \
                lgprntf.c lgsprntf.c memall.c memgrow.c memstat.c \
                stack.c oheapwal.asm tmpalloc.c
LG_OBJS = bugtrak.obj dbg.obj dbgcfg.obj dbgpp.obj datapath.obj exit.obj \
                lgsprntf.obj memall.obj memgrow.obj memstat.obj \
                lgprntf.obj stack.obj oheapwal.obj tmpalloc.obj
LG_HDRS = lg.h lgalt.h dbg.h dbgpp.h datapath.h memmacro.inc dbgmacro.inc \
	memall.h memstat.h bugtrak.h lgprntf.h lgsprntf.h tmpalloc.h
LG_H2I  = lg.inc memall.inc dbg.inc
d16 2
a17 3
DBGMAKEH_SRCS = dbgmakeh.c
DBGMAKEH_OBJS = dbgmakeh.obj
DBGMAKEH_LIBS = lg.lib
d19 3
a21 3
DBGTEST_SRCS = dbgtest.c
DBGTEST_OBJS = dbgtest.obj
DBGTEST_LIBS = _lg.lib _input.lib _mprintf.lib
d23 2
a24 2
STACKTST_OBJS = stacktst.obj
STACKTST_LIBS = lg.lib mprintf.lib
d26 1
a26 4
MFREETST_OBJS = mfreetst.obj
MFREETST_LIBS = _lg.lib mprintf.lib
MFREETST_CFLAGS = -d2
MFREETST_LDFLAGS = debug all
a27 51
%include $(INIT)\make.rc

### OPUS MKMF:  Do not remove this line!  Automatic dependencies follow.

bugtrak.obj objo\bugtrak.obj objd\bugtrak.obj: array.h bugtrak.h dbg.h dbgmacro.h env.h error.h fcntl.h io.h \
	 lg.h lgalt.h lgsprntf.h malloc.h memall.h memmacro.h stat.h \
	 stdarg.h stdio.h string.h time.h types.h

datapath.obj objo\datapath.obj objd\datapath.obj: datapath.h dos.h fcntl.h i86.h malloc.h memall.h memmacro.h \
	 stdarg.h stdio.h stdlib.h string.h types.h

dbg.obj objo\dbg.obj objd\dbg.obj: conio.h ctype.h dbg.h dbgmacro.h error.h kb.h kbcook.h keydefs.h \
	 lg.h lgalt.h lgsprntf.h malloc.h memall.h memmacro.h mprintf.h \
	 stdarg.h stdio.h stdlib.h string.h types.h

dbgcfg.obj objo\dbgcfg.obj objd\dbgcfg.obj: conio.h ctype.h datapath.h dbg.h dbgmacro.h error.h kb.h \
	 kbcook.h keydefs.h lg.h lgalt.h malloc.h memall.h memmacro.h \
	 mprintf.h stdarg.h stdio.h stdlib.h string.h types.h

dbgmakeh.obj objo\dbgmakeh.obj objd\dbgmakeh.obj: conio.h ctype.h dbg.h dbgmacro.h stdarg.h stdio.h stdlib.h \
	 string.h types.h

dbgpp.obj objo\dbgpp.obj objd\dbgpp.obj: dbg.h dbgmacro.h dbgpp.h iostream.h mout.h mprintf.h stddef.h \
	 stdio.h streambu.h string.h strstrea.h types.h

dbgtest.obj objo\dbgtest.obj objd\dbgtest.obj: conio.h datapath.h dbg.h dbgmacro.h lg.h lgalt.h malloc.h \
	 memall.h memmacro.h memstat.h mprintf.h stdarg.h stdio.h stdlib.h \
	 string.h types.h

exit.obj objo\exit.obj objd\exit.obj: dbg.h dbgmacro.h io.h lg.h lgalt.h malloc.h memall.h memmacro.h \
	 stat.h stdio.h stdlib.h string.h types.h

lgprntf.obj objo\lgprntf.obj objd\lgprntf.obj: dbg.h dbgmacro.h io.h lgsprntf.h malloc.h memall.h memmacro.h \
	 stat.h stdarg.h stdio.h tmpalloc.h types.h

lgsprntf.obj objo\lgsprntf.obj objd\lgsprntf.obj: ctype.h fix.h limits.h stdarg.h string.h types.h

memall.obj objo\memall.obj objd\memall.obj: _lg.h dbg.h dbgmacro.h dos.h i86.h malloc.h memall.h memmacro.h \
	 stdio.h string.h types.h

memgrow.obj objo\memgrow.obj objd\memgrow.obj: malloc.h stdio.h string.h

memstat.obj objo\memstat.obj objd\memstat.obj: _lg.h dbg.h dbgmacro.h dos.h i86.h lg.h lgalt.h malloc.h \
	 memall.h memmacro.h memstat.h mprintf.h stdio.h string.h types.h

stack.obj objo\stack.obj objd\stack.obj: dbg.h dbgmacro.h malloc.h memall.h memmacro.h stdio.h types.h

stacktst.obj objo\stacktst.obj objd\stacktst.obj: malloc.h memall.h memmacro.h stdio.h types.h

tmpalloc.obj objo\tmpalloc.obj objd\tmpalloc.obj: _lg.h dbg.h dbgmacro.h malloc.h memall.h memmacro.h stdio.h \
	 tmpalloc.h types.h
@



1.25.1.1
log
@new make regime
@
text
@d7 2
d10 4
a13 2
MAKETOP = $(CWD)
PROJECT = windex
d15 13
a27 2
%include $(MRC)\env.rc
%include $(MRC)\init.rc
d29 9
a37 1
LIBTARGS = lg
d39 3
a41 2
lg_OBJS = bugtrak datapath dbg dbgcfg dbgpp exit lgprntf lgsprntf \
	memall memgrow memstat oheapwal stack tmpalloc
d43 3
a45 3
lg_HDRS = bugtrak.h datapath.h dbg.h dbgmacro.inc dbgpp.h lg.h \
	lgalt.h lgprntf.h lgsprntf.h memall.h memmacro.inc memstat.h \
	tmpalloc.h lg.inc memall.inc dbg.inc
d47 2
a48 2
# can't do
# h2i_files = lg.inc memall.inc dbg.inc
d50 4
a53 1
%include $(MRC)/make.rc
d55 51
@



1.24
log
@Added dbgpp stuff
@
text
@d3 3
a5 3
# $Revision: 1.23 $
# $Author: kaboom $
# $Date: 1994/08/04 22:27:03 $
d24 1
a24 1
PROG_TARGETS = dbgmakeh dbgtest stacktst
d36 1
a36 1
	memall.h memstat.h bugtrak.h lgprntf.h lgsprntf.h tmpalloc.h 
d49 5
@



1.23
log
@added lgprntf, depend.
@
text
@d2 4
a5 4
# $Source$
# $Revision$
# $Author$
# $Date$
d29 1
a29 1
LG_SRCS = bugtrak.c dbg.c dbgcfg.c datapath.c exit.c \
d32 1
a32 1
LG_OBJS = bugtrak.obj dbg.obj dbgcfg.obj datapath.obj exit.obj \
d35 1
a35 1
LG_HDRS = lg.h lgalt.h dbg.h datapath.h memmacro.inc dbgmacro.inc \
d62 2
a63 2
	 lg.h lgalt.h malloc.h memall.h memmacro.h mprintf.h stdarg.h \
	 stdio.h stdlib.h string.h types.h
d72 3
d79 2
a80 2
exit.obj objo\exit.obj objd\exit.obj: dbg.h dbgmacro.h lg.h lgalt.h malloc.h memall.h memmacro.h \
	 stdio.h stdlib.h types.h
@



1.22
log
@ohealwalk
@
text
@a0 4
#	----------------------------------
#	Makefile for DBG library
#	----------------------------------
# $Header: r:/prj/lib/src/lg/rcs/makefile 1.21 1994/07/08 17:39:28 rex Exp $
d2 7
d29 6
a34 5
LG_SRCS = bugtrak.c dbg.c dbgcfg.c datapath.c exit.c memall.c memgrow.c \
		memstat.c stack.c lgsprntf.c tmpalloc.c oheapwal.asm
LG_OBJS = bugtrak.obj dbg.obj dbgcfg.obj datapath.obj exit.obj memall.obj \
		memgrow.obj memstat.obj stack.obj lgsprntf.obj \
                tmpalloc.obj oheapwal.obj
d36 1
a36 1
	memall.h memstat.h bugtrak.h lgsprntf.h tmpalloc.h 
d50 1
a50 1
!include $(INIT)/make.rc
d79 3
d90 1
a90 1
	 memall.h memmacro.h memstat.h stdio.h string.h types.h
d96 2
a97 1
tmpalloc.obj objo\tmpalloc.obj objd\tmpalloc.obj: dbg.h dbgmacro.h malloc.h stdio.h tmpalloc.h types.h
@



1.21
log
@Moved to r:
@
text
@d4 2
a5 63
# $Header: r:/prj/lib/src/lg/rcs/makefile 1.20 1994/06/01 17:14:11 junochoe Exp $
# $Log: makefile $
# Revision 1.20  1994/06/01  17:14:11  junochoe
# added tmpalloc.c temporary allocation functions
# 
# Revision 1.19  1994/02/28  10:53:02  rex
# Changed kb.lib to input.lib
# 
# Revision 1.18  1993/11/03  19:06:12  tjs
# Dependencies
# 
# Revision 1.17  1993/11/03  18:30:29  tjs
# Added lgsprntf
# 
# Revision 1.16  1993/09/30  18:37:28  rex
# Added memgrow.obj
# 
# Revision 1.15  1993/09/13  11:11:17  dfan
# Add memstack stuff
# 
# Revision 1.14  1993/08/11  17:31:47  rex
# Dependencies
# 
# Revision 1.13  1993/08/06  11:00:03  rex
# Dependencies
# 
# Revision 1.12  1993/07/09  09:35:12  rex
# Dependencies
# 
# Revision 1.11  1993/05/01  20:33:02  xemu
# added bugtrak to the LG library
# 
# Revision 1.10  1993/04/22  11:39:53  rex
# Added kb.lib to test prog libs
# 
# Revision 1.9  1993/04/08  10:28:16  rex
# Added MemStat.C
# 
# Revision 1.8  1993/03/24  12:12:37  matt
# install assembly macros header file
# 
# Revision 1.7  1993/03/24  12:02:27  matt
# More asm header junk
# 
# Revision 1.6  1993/03/22  19:10:22  matt
# Added list of .inc files to be converted from .h files.
# 
# Revision 1.5  1993/03/22  18:04:18  rex
# Fixed plurality of DBGMAKEH_SRCS
# 
# Revision 1.4  1993/03/04  18:45:27  rex
# Removed libdbg.h
# 
# Revision 1.3  1993/03/04  11:51:27  rex
# Added exit.c
# /
# 
# Revision 1.2  1993/01/29  17:31:52  rex
# *** empty log message ***
# 
# Revision 1.1  1993/01/29  09:48:03  rex
# Initial revision
# 
d27 1
a27 1
		memstat.c stack.c lgsprntf.c tmpalloc.c
d30 1
a30 1
                tmpalloc.obj
d32 1
a32 1
	memall.h memstat.h bugtrak.h lgsprntf.h tmpalloc.h
@



1.20
log
@added tmpalloc.c temporary allocation functions
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/makefile 1.19 1994/02/28 10:53:02 rex Exp $
d6 3
d74 2
a75 2
SRCDIR = n:\project\lib\src\lg
RELDIR = n:\project\lib\release
@



1.19
log
@Changed kb.lib to input.lib
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/makefile 1.18 1993/11/03 19:06:12 tjs Exp $
d6 3
d85 1
a85 1
		memstat.c stack.c lgsprntf.c
d87 2
a88 1
		memgrow.obj memstat.obj stack.obj lgsprntf.obj
d90 1
a90 1
	memall.h memstat.h bugtrak.h lgsprntf.h
d108 3
a110 3
bugtrak.obj: array.h bugtrak.h dbg.h dbgmacro.h env.h error.h fcntl.h io.h \
	 lg.h lgalt.h malloc.h memall.h memmacro.h mprintf.h stat.h stdio.h \
	 string.h time.h types.h
d112 1
a112 1
datapath.obj: datapath.h dos.h fcntl.h i86.h malloc.h memall.h memmacro.h \
d115 2
a116 1
dbg.obj: dbg.h dbgmacro.h malloc.h memall.h memmacro.h mprintf.h stdarg.h \
d119 3
a121 3
dbgcfg.obj: conio.h ctype.h datapath.h dbg.h dbgmacro.h error.h kb.h \
	 kbcook.h lg.h lgalt.h malloc.h memall.h memmacro.h mprintf.h \
	 stdarg.h stdio.h stdlib.h string.h types.h
d123 1
a123 1
dbgmakeh.obj: conio.h ctype.h dbg.h dbgmacro.h stdarg.h stdio.h stdlib.h \
d126 1
a126 1
dbgtest.obj: conio.h datapath.h dbg.h dbgmacro.h lg.h lgalt.h malloc.h \
d130 1
a130 1
exit.obj: dbg.h dbgmacro.h lg.h lgalt.h malloc.h memall.h memmacro.h \
d133 1
a133 1
lgsprntf.obj: ctype.h fix.h limits.h stdarg.h string.h types.h
d135 1
a135 1
memall.obj: _lg.h dbg.h dbgmacro.h dos.h i86.h malloc.h memall.h memmacro.h \
d138 1
a138 1
memgrow.obj: malloc.h stdio.h string.h
d140 1
a140 1
memstat.obj: _lg.h dbg.h dbgmacro.h dos.h i86.h lg.h lgalt.h malloc.h \
d143 1
a143 1
stack.obj: dbg.h dbgmacro.h malloc.h memall.h memmacro.h stdio.h types.h
d145 3
a147 1
stacktst.obj: malloc.h memall.h memmacro.h stdio.h types.h
@



1.18
log
@Dependencies
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/makefile 1.17 1993/11/03 18:30:29 tjs Exp $
d6 3
d95 1
a95 1
DBGTEST_LIBS = lg.lib kb.lib mprintf.lib
@



1.17
log
@Added lgsprntf
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/makefile 1.16 1993/09/30 18:37:28 rex Exp $
d6 3
d124 2
@



1.16
log
@Added memgrow.obj
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/makefile 1.15 1993/09/13 11:11:17 dfan Exp $
d6 3
d76 1
a76 1
		memstat.c stack.c
d78 1
a78 1
		memgrow.obj memstat.obj stack.obj
d80 1
a80 1
	memall.h memstat.h bugtrak.h
@



1.15
log
@Add memstack stuff
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/makefile 1.14 1993/08/11 17:31:47 rex Exp $
d6 3
d72 4
a75 3
LG_SRCS = dbg.c dbgcfg.c datapath.c exit.c memall.c memstat.c bugtrak.c
LG_OBJS = dbg.obj dbgcfg.obj datapath.obj exit.obj memall.obj memstat.obj \
        bugtrak.obj stack.obj
d122 8
a129 2
memstat.obj: dbg.h dbgmacro.h dos.h i86.h lg.h lgalt.h malloc.h memall.h \
	 memmacro.h memstat.h stdio.h string.h types.h
@



1.14
log
@Dependencies
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/makefile 1.13 1993/08/06 11:00:03 rex Exp $
d6 3
d64 1
a64 1
PROG_TARGETS = dbgmakeh dbgtest
d71 1
a71 1
        bugtrak.obj
d83 3
@



1.13
log
@Dependencies
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/makefile 1.12 1993/07/09 09:35:12 rex Exp $
d6 3
d109 1
a109 1
memall.obj: dbg.h dbgmacro.h dos.h i86.h malloc.h memall.h memmacro.h \
@



1.12
log
@Dependencies
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/makefile 1.11 1993/05/01 20:33:02 xemu Exp $
d6 3
d83 2
a84 2
	 lg.h lgalt.h libdbg.h malloc.h memall.h memmacro.h mprintf.h \
	 stat.h stdio.h string.h time.h types.h
d93 2
a94 2
	 kbcook.h lg.h lgalt.h libdbg.h malloc.h memall.h memmacro.h \
	 mprintf.h stdarg.h stdio.h stdlib.h string.h types.h
d99 3
a101 3
dbgtest.obj: conio.h datapath.h dbg.h dbgmacro.h lg.h lgalt.h libdbg.h \
	 malloc.h memall.h memmacro.h memstat.h mprintf.h stdarg.h stdio.h \
	 stdlib.h string.h types.h
d103 2
a104 2
exit.obj: dbg.h dbgmacro.h lg.h lgalt.h libdbg.h malloc.h memall.h \
	 memmacro.h stdio.h stdlib.h types.h
d109 2
a110 2
memstat.obj: dbg.h dbgmacro.h dos.h i86.h lg.h lgalt.h libdbg.h malloc.h \
	 memall.h memmacro.h memstat.h stdio.h string.h types.h
@



1.11
log
@added bugtrak to the LG library
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/makefile 1.10 1993/04/22 11:39:53 rex Exp $
d6 3
d73 1
a73 1
DBGTEST_LIBS = lg.lib mprintf.lib kb.lib
a74 1

d79 3
a81 2
datapath.obj: datapath.h malloc.h memall.h memmacro.h stdio.h string.h \
	 types.h
d83 3
d89 3
a91 2
dbgcfg.obj: conio.h ctype.h datapath.h dbg.h dbgmacro.h mprintf.h stdarg.h \
	 stdio.h stdlib.h string.h types.h
d106 2
a107 2
memstat.obj: malloc.h memstat.h string.h types.h

@



1.10
log
@Added kb.lib to test prog libs
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/makefile 1.9 1993/04/08 10:28:16 rex Exp $
d6 3
d57 3
a59 2
LG_SRCS = dbg.c dbgcfg.c datapath.c exit.c memall.c memstat.c
LG_OBJS = dbg.obj dbgcfg.obj datapath.obj exit.obj memall.obj memstat.obj
d61 1
a61 1
	memall.h memstat.h
d100 1
@



1.9
log
@Added MemStat.C
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/makefile 1.8 1993/03/24 12:12:37 matt Exp $
d6 3
d66 1
a66 1
DBGTEST_LIBS = lg.lib mprintf.lib
@



1.8
log
@install assembly macros header file
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/makefile 1.7 1993/03/24 12:02:27 matt Exp $
d6 3
d51 4
a54 3
LG_SRCS = memall.c dbg.c dbgcfg.c datapath.c exit.c
LG_OBJS = memall.obj dbg.obj dbgcfg.obj datapath.obj exit.obj
LG_HDRS = lg.h lgalt.h memall.h dbg.h datapath.h memmacro.inc dbgmacro.inc
d70 2
a71 1
datapath.obj: datapath.h malloc.h memall.h stdio.h string.h types.h
d73 7
a79 1
dbg.obj: dbg.h malloc.h memall.h mprintf.h stdarg.h stdio.h stdlib.h \
d82 2
a83 1
dbgcfg.obj: conio.h ctype.h datapath.h dbg.h mprintf.h stdarg.h stdio.h \
d86 2
a87 2
dbgmakeh.obj: conio.h ctype.h dbg.h stdarg.h stdio.h stdlib.h string.h \
	 types.h
d89 2
a90 2
dbgtest.obj: conio.h dbg.h lg.h lgalt.h libdbg.h malloc.h memall.h \
	 mprintf.h stdarg.h stdio.h stdlib.h string.h types.h
d92 1
a92 4
exit.obj: dbg.h lg.h lgalt.h libdbg.h malloc.h memall.h stdio.h stdlib.h \
	 types.h

memall.obj: dbg.h dos.h i86.h malloc.h memall.h stdio.h string.h types.h
@



1.7
log
@More asm header junk
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/makefile 1.6 1993/03/22 19:10:22 matt Exp $
d6 3
d50 2
a51 2
LG_HDRS = lg.h lgalt.h memall.h dbg.h datapath.h memmacro.inc
LG_H2I  = lg.inc memall.inc
@



1.6
log
@Added list of .inc files to be converted from .h files.
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/makefile 1.5 1993/03/22 18:04:18 rex Exp $
d6 3
d47 1
a47 1
LG_HDRS = lg.h lgalt.h memall.h dbg.h datapath.h
@



1.5
log
@Fixed plurality of DBGMAKEH_SRCS
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/makefile 1.4 1993/03/04 18:45:27 rex Exp $
d6 3
d45 1
@



1.4
log
@Removed libdbg.h
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/makefile 1.3 1993/03/04 11:51:27 rex Exp $
d6 3
d43 1
a43 1
DBGMAKEH_SRC = dbgmakeh.c
@



1.3
log
@Added exit.c
/
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/makefile 1.2 1993/01/29 17:31:52 rex Exp $
d6 4
d34 1
a34 1
EXTRA_TARGETS = libdbg.h
d38 1
a38 1
LG_HDRS = lg.h lgalt.h memall.h dbg.h datapath.h libdbg.h
d53 1
a53 2
datapath.obj: malloc.h stdio.h string.h \
	 datapath.h types.h
d55 2
a56 2
dbg.obj: stdarg.h stdio.h stdlib.h \
	 string.h dbg.h mprintf.h types.h
d58 2
a59 3
dbgcfg.obj: conio.h ctype.h stdarg.h \
	 stdio.h stdlib.h string.h datapath.h \
	 dbg.h mprintf.h types.h
d61 2
a62 2
dbgmakeh.obj: conio.h ctype.h stdarg.h \
	 stdio.h stdlib.h string.h dbg.h types.h
d64 2
a65 3
dbgtest.obj: conio.h malloc.h stdarg.h \
	 stdio.h string.h dbg.h lg.h lgalt.h libdbg.h \
	 memall.h types.h
d67 4
a70 2
memall.obj: dos.h i86.h malloc.h \
	 stdio.h dbg.h memall.h types.h
@



1.2
log
@*** empty log message ***
@
text
@d4 1
a4 1
# $Header: n:/project/lib/src/lg/rcs/rcs/makefile 1.1 1993/01/29 09:48:03 rex Exp $
d6 3
d13 5
d32 2
a33 2
LG_SRCS = memall.c dbg.c dbgcfg.c datapath.c
LG_OBJS = memall.obj dbg.obj dbgcfg.obj datapath.obj
d43 1
@



1.1
log
@Initial revision
@
text
@d4 5
a8 2
# $Header: $
# $Log: $
d16 1
@

