#
# $Source: x:/prj/tech/libsrc/md/RCS/makefile $
# $Revision: 1.9 $
# $Author: JAEMZ $
# $Date: 1998/06/29 14:32:33 $
#
# Makefile for MD library
#

MAKETOP = $(CWD)

PROJECT = tech

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS = md

md_OBJS = render debug utils light scale shear fancy hitdet mipmap

md_HDRS= md.h md_.h mds.h mdd.h mdutil.h

%include $(MRC)\make.rc


